import { useTranslation } from 'react-i18next'
import { KeymapSection } from '../KeymapSection'
import keymapStyles from '../Keymap.module.css'
import styles from './Touchpad.module.css'
import { SectionActions } from '../SectionActions'

type Card = { mode:string; dualStageMode:string; gridColumns:number; gridRows:number; sensitivity?:number; onModeChange?:(v:string)=>void; onGridSizeChange?:(c:number,r:number)=>void; onSensitivityChange?:(v:string)=>void; onDualStageModeChange?:(v:string)=>void }
type Props = { left?:Card; right?:Card; lightTouchThreshold?:number; onLightTouchThresholdChange?:(v:string)=>void; touchpadMode:string; touchpadDualStageMode:string; gridColumns:number; gridRows:number; onTouchpadModeChange?:(v:string)=>void; onGridSizeChange?:(c:number,r:number)=>void; touchpadSensitivity?:number; onTouchpadSensitivityChange?:(v:string)=>void; onTouchpadDualStageModeChange?:(v:string)=>void; warnings?:string[]; hasPendingChanges:boolean; statusMessage?:string|null; onApply:()=>void; onCancel:()=>void; applyDisabled?:boolean }
const modes=['NO_FULL','NO_SKIP','NO_SKIP_EXCLUSIVE','MUST_SKIP','MAY_SKIP','MUST_SKIP_R','MAY_SKIP_R']
function CardView({config,title}:{config:Card;title:string}) { const {t}=useTranslation(); return <div className={styles.touchpadCard}><h4>{title}</h4><label>{t('keymap.mode')}<select className="app-select" value={config.mode} onChange={e=>config.onModeChange?.(e.target.value)}><option value="">{t('common.noneSelected')}</option><option value="GRID_AND_STICK">{t('keymap.gridAndStick')}</option><option value="MOUSE">{t('keymap.mouse')}</option><option value="PS_TOUCHPAD">{t('keymap.psTouchpad')}</option></select></label><label>{t('keymap.touchpadDualStageMode')}<select className="app-select" value={config.dualStageMode||'NO_SKIP'} onChange={e=>config.onDualStageModeChange?.(e.target.value)}>{modes.map(v=><option key={v} value={v}>{v}</option>)}</select></label>{config.mode==='GRID_AND_STICK'&&<div className={styles.gridSizeInputs}><label>{t('keymap.columns')}<input type="number" min={1} max={5} value={config.gridColumns} onChange={e=>config.onGridSizeChange?.(Number(e.target.value)||1,config.gridRows)}/></label><label>{t('keymap.rows')}<input type="number" min={1} max={5} value={config.gridRows} onChange={e=>config.onGridSizeChange?.(config.gridColumns,Number(e.target.value)||1)}/></label></div>}{config.mode==='MOUSE'&&<label>{t('keymap.touchpadSensitivity')}<input type="number" step="0.1" value={config.sensitivity??''} onChange={e=>config.onSensitivityChange?.(e.target.value)}/></label>}</div> }
export function TouchpadSettingsSection(props:Props) { const {t}=useTranslation(); const {left,right}=props; return <><KeymapSection title={t('keymap.touchpadSettingsTitle')} description={t('keymap.touchpadSettingsDescription')}><div className={styles.touchpadSettings}><label>{t('keymap.touchpadLightTouchThreshold','Light-touch threshold')}<input type="number" min="0" max="1" step="0.01" value={props.lightTouchThreshold ?? 0.01} onChange={e=>props.onLightTouchThresholdChange?.(e.target.value)}/></label>{left&&right?<div className={styles.touchpadSettings}><CardView config={left} title={t('keymap.leftTouchpad','Left touchpad')}/><CardView config={right} title={t('keymap.rightTouchpad','Right touchpad')}/></div>:<CardView config={{mode:props.touchpadMode,dualStageMode:props.touchpadDualStageMode,gridColumns:props.gridColumns,gridRows:props.gridRows,sensitivity:props.touchpadSensitivity,onModeChange:props.onTouchpadModeChange,onGridSizeChange:props.onGridSizeChange,onSensitivityChange:props.onTouchpadSensitivityChange,onDualStageModeChange:props.onTouchpadDualStageModeChange}} title={t('keymap.touchpad','Touchpad')}/>} {props.warnings?.map((w,i)=><div key={i} className={styles.touchpadWarning}>{w}</div>)}</div></KeymapSection><SectionActions className={keymapStyles.keymapSectionActions} hasPendingChanges={props.hasPendingChanges} statusMessage={props.statusMessage} onApply={props.onApply} onCancel={props.onCancel} applyDisabled={props.applyDisabled}/></> }
