const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const Module = require('node:module')
const app = path.resolve(__dirname, '../JSM_GUI/jsm_gui_tauri')
const ts = require(path.join(app, 'node_modules/typescript'))
const cache = new Map()
function load(file) {
  file = path.resolve(file)
  if (cache.has(file)) return cache.get(file).exports
  const mod = new Module(file); cache.set(file, mod); mod.filename = file
  mod.paths = Module._nodeModulePaths(path.dirname(file))
  mod.require = name => name.startsWith('.') ? load(path.resolve(path.dirname(file), name + '.ts')) : require(name)
  mod._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS } }).outputText, file)
  return mod.exports
}
const k = load(path.join(app, 'src/utils/keymap.ts'))
const { parseConfigText, serializeConfig } = load(path.join(app, 'src/utils/configSerializer.ts'))
const m = load(path.join(app, 'src/utils/modeshift.ts'))
const labels = load(path.join(app, 'src/utils/bindingLabels.ts'))
const includes = load(path.join(app, 'src/utils/configIncludes.ts'))
const registry = fs.readFileSync(path.resolve(__dirname, '../JoyShockMapper/JoyShockMapper/src/main.cpp'), 'utf8')
const registrations = [...registry.matchAll(/new JSMAssignment<Mapping>\("(SL|SR)", "([A-Z]+)"/g)].map(match => [match[1], match[2]])
assert.deepEqual(registrations, [['SL','LSL'], ['SL','RSL'], ['SR','LSR'], ['SR','RSR']], 'shared-target UI contract follows native registrations')
const source = 'RESET_MAPPINGS\nLSL = Q\nSL = A B # shared note\nL,SL = C # shared chord\nL,LSL = D\nN+SR = E\nUP*SR = F\nLSL,SL = G\nSL,SL = INVALID_NATIVE_CONDITION\nUNKNOWN_ALIAS = preserve exactly\n'
assert.equal(k.getKeymapValue(source, 'LSL'), 'A B')
assert.equal(k.getKeymapValue(source, 'RSL'), 'A B')
assert.equal(k.getKeymapValue(source, 'L,LSL'), 'D')
assert.equal(k.getKeymapValue(source, 'L,RSL'), 'C')
assert.equal(k.getKeymapValue(source, 'LSL,LSL'), 'G', 'valid physical chord to a shared target is double press only on that physical target')
assert.equal(k.getKeymapValue('SL,SL = Q\n', 'LSL,LSL'), undefined, 'aliases must not become fictional input conditions')
for (const target of ['LSL', 'RSL']) assert.deepEqual(k.getButtonBindingSet(source, target).tap, 'A')
let edited = k.setTapBinding(source, 'LSL', 'Z')
assert.equal(k.getKeymapValue(edited, 'LSL'), 'Z B')
assert.equal(k.getKeymapValue(edited, 'RSL'), 'A B', 'editing one input leaves its shared sibling untouched')
assert.match(edited, /SL = A B # shared note/)
edited = k.setHoldBinding(edited, 'LSL', null)
edited = k.setTapBinding(edited, 'LSL', null)
assert.equal(k.getKeymapValue(edited, 'LSL'), 'NONE', 'clearing an input overrides the shared binding instead of revealing it again')
assert.equal(k.getKeymapValue(edited, 'RSL'), 'A B')
for (const [target, slot, modifier, expected] of [['RSL','chord','L','C'], ['LSR','simultaneous','N','E'], ['RSR','diagonal','UP','F']]) {
  const rows = k.getButtonBindingRows(source, target).filter(row => row.slot === slot && row.modifierCommand === modifier)
  assert.equal(rows.length, 1)
  assert.equal(rows[0].binding, expected)
  const next = k.setComboBindingLine(source, target, slot, rows[0].id, modifier, 'Z')
  const separator = {chord:',',simultaneous:'+',diagonal:'*'}[slot]
  assert.equal(k.getKeymapValue(next, modifier + separator + target), 'Z')
  const cleared = k.removeComboBindingLine(next, target, slot, rows[0].id)
  assert.equal(k.getKeymapValue(cleared, modifier + separator + target), 'NONE')
  assert.match(next, /L,SL = C # shared chord/)
}
assert.equal(k.getButtonBindingRows(source, 'LSL').filter(row => row.slot === 'chord' && row.modifierCommand === 'L').length, 1, 'last individual override replaces its alias in the GUI')
for (const text of [source, edited, 'SR = A\nLSR = B\n', 'LSR = B\nSR = A\n']) {
  const saved = serializeConfig(parseConfigText(text))
  for (const key of ['SL','SR','LSL','RSL','LSR','RSR','L,LSL','L,RSL','N+LSR','UP*RSR']) {
    assert.equal(k.getKeymapValue(saved, key), k.getKeymapValue(text, key), 'serialization preserves native alias precedence: ' + key)
  }
  if (text.includes('UNKNOWN_ALIAS')) assert.match(saved, /UNKNOWN_ALIAS = preserve exactly/)
}
console.log('PASS: shared native target aliases, individual edits/clear, chord/double/sim/diagonal distinctions, sibling isolation and saved precedence')
const target = { id: 'rear', title: 'Rear input', buttons: [{ command: 'LSL', label: 'L4' }] }
assert.ok(!m.modeshiftTriggers(source, target).includes('SL'), 'target aliases are never fictional held inputs')
const shifted = 'LSL = Q\nSL = A\nL,SL = B # shared shift\nL,LSL = C\n# @label L,SL = Shared\n'
assert.deepEqual(m.modeshiftTriggers(shifted, target), ['L'])
assert.equal(m.modeshiftCount(shifted, 'RSL'), 1)
assert.deepEqual(m.modeshiftsOn(shifted, 'LSL'), [{ trigger: 'L', value: 'C' }])
assert.equal(m.readModeshift(shifted, 'L', 'RSL'), 'B')
const projection = m.projectModeshift(shifted, 'L')
assert.equal(k.getKeymapValue(projection, 'LSL'), 'C')
assert.equal(k.getKeymapValue(projection, 'RSL'), 'B')
const folded = m.foldModeshift(shifted, 'L', k.setTapBinding(projection, 'LSL', 'Z'), {}, projection)
assert.equal(m.readModeshift(folded, 'L', 'LSL'), 'Z')
assert.equal(m.readModeshift(folded, 'L', 'RSL'), 'B')
const removed = m.removeModeshift(shifted, target, 'L')
assert.equal(m.readModeshift(removed, 'L', 'LSL'), undefined)
assert.equal(m.readModeshift(removed, 'L', 'RSL'), 'B')
assert.match(removed, /# @label L,RSL = Shared/)
const renamed = m.renameModeshift(shifted, target, 'L', 'R')
assert.equal(m.readModeshift(renamed, 'R', 'LSL'), 'C')
assert.equal(m.readModeshift(renamed, 'L', 'RSL'), 'B')
assert.equal(m.readModeshift(renamed, 'R', 'RSL'), undefined)
console.log('PASS: alias-aware modeshift discovery, projection, scoped edit, rename and remove preserve the sibling')
const annotated = '# @label SL = Shared\n# @label LSL = Individual\n# @label L,SR::BASE%3AA::0 = Alternate\n'
assert.equal(labels.getBindingLabel(annotated, 'RSL'), 'Shared')
assert.equal(labels.getBindingLabel(annotated, 'LSL'), 'Individual')
assert.equal(labels.getBindingLabel(annotated, 'L,RSR::BASE%3AA::0'), 'Alternate')
const unnamed = labels.setBindingLabel(annotated, 'RSL', '', { keepEmpty: true })
assert.equal(labels.getBindingLabel(unnamed, 'RSL'), '')
assert.equal(labels.getBindingLabel(unnamed, 'LSL'), 'Individual')
const resolved = includes.resolveIncludes('<editor>', { '<editor>': 'Template.txt\nLSL = Z\n', 'Template.txt': 'SL = A\n' })
assert.equal(resolved.origins.LSL, '<editor>')
assert.equal(resolved.origins.RSL, 'Template.txt')
const reversed = includes.resolveIncludes('<editor>', { '<editor>': 'LSL = Z\nTemplate.txt\n', 'Template.txt': 'SL = A\n' })
assert.equal(reversed.origins.LSL, 'Template.txt', 'alias source follows native order even after an earlier individual')
console.log('PASS: shared labels, per-output annotations, individual unnamed override and import-origin precedence')
