const assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require('C:/Users/luker/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/platform/desktopBridge.ts*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text())+'\nwindow.__chordTestBridge=desktopBridge; if(window.__installChordFixture) window.__installChordFixture(desktopBridge);\n'});});
 await page.goto('http://127.0.0.1:1420/?mock');
 const onboarding=page.getByRole('dialog',{name:'Controller power-on sound'});if(await onboarding.waitFor({state:'visible',timeout:3000}).then(()=>true).catch(()=>false))await onboarding.getByRole('button',{name:'Keep them',exact:true}).click();
 await page.evaluate(async()=>{
  const install=bridge=>{
  window.testChords=[{id:'builtin-default',buttons:[],triggerGroups:[['HOME'],['MISC1']],profilePath:'profiles-library/Default Global Chords.txt'}];
  window.testProfiles={'Default Global Chords':'RESET_MAPPINGS\nW = "OPEN_KEYBOARD"\nRSL = "TOGGLE_MAPPING"\nRSR = "CALIBRATE_GYRO"\n'};
  bridge.listGlobalChords=async()=>window.testChords;
  bridge.listLibraryProfiles=async()=>Object.keys(window.testProfiles);
  bridge.loadLibraryProfile=async name=>({name,content:window.testProfiles[name]});
  bridge.createLibraryProfile=async name=>({name,path:`profiles-library/${name}.txt`,content:''});
  bridge.saveLibraryProfile=async(name,content)=>{window.testProfiles[name]=content;return {name}};
  bridge.saveGlobalChord=async chord=>{window.testChords=window.testChords.filter(c=>c.id!==chord.id).concat(chord);return window.testChords};
  bridge.deleteGlobalChord=async id=>{window.testChords=window.testChords.filter(c=>c.id!==id);return window.testChords};
  };window.__installChordFixture=install;install(window.__chordTestBridge);
 });
 const go=()=>page.getByRole('button',{name:/Global chords/i}).first().click();await go();
 await page.getByText('Built-in',{exact:true}).waitFor();assert.equal(await page.getByText('Built-in',{exact:true}).count(),1);
 assert.equal(await page.getByText('Reserved',{exact:true}).count(),0);
 const row=page.locator('[class*="rowMain"]').first();await row.click();
 assert.equal(await page.getByRole('combobox',{name:'Open keyboard button'}).count(),0);
 await page.getByRole('button',{name:'Add OR alternative'}).click();
 const groups=page.locator('[class*="triggerGroup"]');assert.equal(await groups.count(),3);
 await groups.nth(2).getByRole('button',{name:'A',exact:true}).click();
 await groups.nth(2).getByRole('button',{name:'B',exact:true}).click();
 assert.deepEqual(await page.evaluate(()=>window.testChords[0].triggerGroups),[['HOME'],['MISC1'],['S','E']]);
 await row.evaluate(e=>{document.body.dataset.inputSource='controller';e.focus()});await page.waitForTimeout(600);
 assert.equal(await row.evaluate(e=>getComputedStyle(e.parentElement.parentElement).boxShadow),'none');
 await page.screenshot({path:path.join(__dirname,'../tmp/global-chords-alternatives.png')});
 await page.getByRole('button',{name:'Edit',exact:true}).first().click();
 const modal=page.getByRole('dialog',{name:'Built-in configuration'});await modal.waitFor();
 await page.evaluate(()=>window.__pad.live('profiles-library/Default Global Chords.txt'));
 await page.waitForFunction(()=>document.activeElement?.textContent==='Cancel');
 await page.evaluate(()=>window.__pad.press(['RIGHT']));
 await page.waitForFunction(()=>document.activeElement?.textContent==='Clone as Personal');
 await page.evaluate(()=>window.__pad.press(['S']));await modal.waitFor({state:'hidden'});
 assert.ok(await page.evaluate(()=>window.testProfiles['Personal Default Global Chords'].includes('W = "OPEN_KEYBOARD"')));
 assert.equal(await page.evaluate(()=>window.testChords.length),2);
 await page.evaluate(()=>window.__pad.live('AppNavigation.txt'));
 await page.getByRole('button',{name:/^Home/}).first().click();await go();
 await page.getByText('Built-in',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Remove',exact:true}).first().click();
 const remove=page.getByRole('alertdialog');await remove.getByRole('button',{name:'Remove chord',exact:true}).click();
 assert.equal(await page.evaluate(()=>window.testChords.some(c=>c.id==='builtin-default')),false);
 await page.getByRole('button',{name:/^Configurations/}).first().click();
 const libraryRow=page.locator('[data-profile="Default Global Chords"]');await libraryRow.locator('button').first().click();
 const detail=page.getByRole('complementary',{name:'Default Global Chords details'});
 assert.equal(await detail.getByRole('button',{name:'Delete',exact:true}).count(),0);
 assert.equal(await detail.getByRole('button',{name:'Rename',exact:true}).count(),0);
 await detail.getByRole('button',{name:/Edit/}).first().click();
 const libraryDialog=page.getByRole('dialog',{name:'Built-in configuration'});await libraryDialog.waitFor();
 await page.evaluate(()=>window.__pad.live('profiles-library/Default Global Chords.txt'));
 await page.waitForFunction(()=>document.activeElement?.textContent==='Cancel');
 await page.evaluate(()=>window.__pad.press(['RIGHT']));await page.waitForFunction(()=>document.activeElement?.textContent==='Clone as Personal');
 await page.evaluate(()=>window.__pad.press(['E']));await libraryDialog.waitFor({state:'hidden'});
 await page.evaluate(()=>window.__pad.live('AppNavigation.txt'));
 await page.getByRole('button',{name:/^Preferences/}).first().click();
 await page.getByRole('button',{name:'Reset default settings',exact:true}).click();
 const reset=page.getByRole('alertdialog',{name:'Reset default settings?'});await reset.waitFor();
 await page.evaluate(()=>window.__pad.press(['E']));await reset.waitFor({state:'hidden'});
 assert.deepEqual(errors,[]);console.log('PASS: one row, OR of AND groups, editable/removable default activation, regular keyboard command, controller clone/reset dialogs, single focus highlight.');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
