const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')

const mapper = path.join(__dirname, '../JoyShockMapper/JoyShockMapper')
const vcvars = 'C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Auxiliary/Build/vcvars64.bat'
if (!fs.existsSync(vcvars)) throw new Error('MSVC build tools are required for the tone sequence test')
const work = fs.mkdtempSync(path.join(os.tmpdir(), 'jsm-tones-'))
const source = path.join(mapper, 'tests/tone_sequence_tests.cpp')
const exe = path.join(work, 'tone_sequence_tests.exe')
const bat = path.join(work, 'build.bat')
fs.writeFileSync(bat, `@echo off\r\nset "PATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer;%PATH%"\r\ncall "${vcvars}" >nul\r\ncl /nologo /EHsc /std:c++17 /I "${path.join(mapper, 'include')}" "${source}" /Fe:"${exe}"\r\n`)
const env = Object.fromEntries(Object.entries(process.env).map(([key, value]) => [key.toUpperCase(), value]))
const build = spawnSync('cmd.exe', ['/d', '/c', bat], { cwd: work, encoding: 'utf8', env })
assert.equal(build.status, 0, `Tone sequence compile failed:\n${build.stdout}${build.stderr}`)
const run = spawnSync(exe, { encoding: 'utf8', env })
assert.equal(run.status, 0, `Tone sequence test failed:\n${run.stdout}${run.stderr}`)
assert.match(run.stdout, /tone_sequence_tests passed/)
console.log(run.stdout.trim())
