const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '../JSM_GUI/jsm_gui_tauri')
const ts = require(path.join(root, 'node_modules/typescript'))
const cache = new Map()
function load(file) {
  file = path.resolve(root, file)
  if (cache.has(file)) return cache.get(file)
  const module = { exports: {} }; cache.set(file, module.exports)
  const code = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText
  new Function('module', 'exports', 'require', code)(module, module.exports, name => name.startsWith('.') ? load(path.resolve(path.dirname(file), name) + '.ts') : require(name))
  cache.set(file, module.exports); return module.exports
}
const v = load('src/utils/virtualStickSettings.ts')
const { parseConfigText, serializeConfig } = load('src/utils/configSerializer.ts')
const { getKeymapValue } = load('src/utils/keymap.ts')
const { readLayers, writeLayers, projectLayer, foldLayer } = load('src/utils/layers.ts')
const source = ['# This profile is controller-only', 'RESET_MAPPINGS', 'VIRTUAL_CONTROLLER = XBOX', 'GYRO_OUTPUT = RIGHT_STICK',
  'RIGHT_STICK_UNDEADZONE_INNER = 0.2 # measured in game', 'RIGHT_STICK_UNDEADZONE_OUTER = 0.05', 'RIGHT_STICK_UNPOWER = 2',
  'LEFT_STICK_UNDEADZONE_INNER = 0.1', 'LEFT_TOUCHPAD_MODE = GRID_AND_STICK', 'RIGHT_TOUCHPAD_MODE = MOUSE',
  'R,GYRO_OUTPUT = LEFT_STICK', 'R,LEFT_STICK_UNDEADZONE_INNER = 0.25', 'W = !1\\ ^2_ !3/ -4+',
  'UNKNOWN_FUTURE_KEY = "retain this # quoted value" # retain this note', '# arbitrary custom note', ''].join('\n')
let text = v.writeVirtualStickNumber(source, 'RIGHT_STICK', 'UNDEADZONE_INNER', 0.21)
assert.equal(getKeymapValue(text, 'LEFT_STICK_UNDEADZONE_INNER'), '0.1')
assert.match(text, /RIGHT_STICK_UNDEADZONE_INNER = 0.21 # measured in game/)
assert.equal(getKeymapValue(text, 'LEFT_TOUCHPAD_MODE'), 'GRID_AND_STICK')
assert.equal(getKeymapValue(text, 'RIGHT_TOUCHPAD_MODE'), 'MOUSE')
assert.equal(v.writeVirtualStickNumber(text, 'RIGHT_STICK', 'UNDEADZONE_INNER', 0.99), text)
assert.equal(v.writeVirtualStickNumber(text, 'RIGHT_STICK', 'UNPOWER', NaN), text)
assert.equal(v.writeVirtualStickNumber(text, 'RIGHT_STICK', 'UNPOWER', -1), text)
text = v.writeVirtualStickNumber(text, 'LEFT_STICK', 'UNPOWER', 3, text, 'R,')
assert.equal(getKeymapValue(text, 'R,LEFT_STICK_UNPOWER'), '3')
assert.equal(getKeymapValue(text, 'RIGHT_STICK_UNPOWER'), '2')
assert.equal(v.virtualStickValues(text, 'LEFT_STICK', 'R,').inner, 0.25)
assert.equal(v.virtualStickValues(text, 'LEFT_STICK', 'R,').maxSpeed, 360)
assert.equal(v.readVirtualSetting(text, 'VIRTUAL_CONTROLLER'), 'XBOX')
text = v.writeVirtualSetting(text, 'GYRO_OUTPUT', 'MOUSE')
assert.equal(getKeymapValue(text, 'GYRO_OUTPUT'), 'MOUSE')
assert.equal(getKeymapValue(text, 'RIGHT_STICK_UNPOWER'), '2', 'switching modes preserves tuning')
const saved = serializeConfig(parseConfigText(text))
assert.ok(saved.indexOf('VIRTUAL_CONTROLLER = XBOX') < saved.indexOf('GYRO_OUTPUT = MOUSE'), 'device must exist before dependent gyro assignment')
assert.ok(saved.indexOf('VIRTUAL_CONTROLLER = XBOX') < saved.indexOf('W = '), 'device precedes output bindings')
assert.match(saved, /UNKNOWN_FUTURE_KEY = "retain this # quoted value" # retain this note/)
assert.match(saved, /R,LEFT_STICK_UNPOWER = 3/)
assert.equal(serializeConfig(parseConfigText(saved)), saved)
assert.equal(v.correctedStickRadius(0, 0.2, 0.05, 2), 0.2, 'native at-rest deadzone probe')
assert.equal(v.correctedStickRadius(0, 0.2, 0.05, 2, false), 0, 'normal idle output when probe is disabled')
assert.equal(v.virtualStickValues(source, 'RIGHT_STICK').probe, true, 'legacy profiles keep the test signal')
const noProbe = v.writeVirtualSetting(source, 'RIGHT_STICK_DEADZONE_PROBE', 'OFF')
assert.equal(v.virtualStickValues(noProbe, 'RIGHT_STICK').probe, false)
assert.equal(v.virtualStickValues(noProbe, 'LEFT_STICK').probe, true)
const heldProbe = v.writeVirtualSetting(noProbe, 'LEFT_STICK_DEADZONE_PROBE', 'OFF', 'R,')
const hapticSettings = v.writeVirtualSetting('GYRO_HAPTIC_INTENSITY = 0\nL,GYRO_HAPTIC_INTENSITY = 20 # ADS\n', 'GYRO_HAPTIC_INTENSITY', 25, 'L,')
assert.equal(v.readVirtualSetting(hapticSettings, 'GYRO_HAPTIC_INTENSITY'), '0')
assert.equal(v.readVirtualSetting(hapticSettings, 'GYRO_HAPTIC_INTENSITY', 'L,'), '25')
assert.match(serializeConfig(parseConfigText(hapticSettings)), /L,GYRO_HAPTIC_INTENSITY = 25 # ADS/)
assert.equal(v.virtualStickValues(heldProbe, 'LEFT_STICK', 'R,').probe, false)
assert.equal(v.virtualStickValues(heldProbe, 'LEFT_STICK').probe, true)
assert.match(serializeConfig(parseConfigText(heldProbe)), /R,LEFT_STICK_DEADZONE_PROBE = OFF/)
assert.equal(v.correctedStickRadius(1, 0.2, 0.05, 2), 0.95)
assert.ok(Math.abs(v.correctedStickRadius(0.25, 0.2, 0.05, 2) - 0.575) < 1e-8)
assert.equal(v.correctedStickRadius(0.00001, 0.2, 0.05, 1), 0, 'native cutoff below one percent')
assert.equal(v.virtualStickProblem({ inner: 0.9, outer: 0.2, exponent: 1, scale: 1, maxSpeed: 360 }), 'Inner and outer range corrections must total less than 100%.')
const layered = writeLayers(source, [{ id: 'ads', name: 'ADS', overrides: { GYRO_OUTPUT: 'LEFT_STICK' } }])
const projected = projectLayer(layered, 'ads')
const edited = v.writeVirtualStickNumber(projected, 'LEFT_STICK', 'UNDEADZONE_INNER', 0.3)
const folded = foldLayer(layered, 'ads', edited, projected)
assert.equal(readLayers(folded)[0].overrides.LEFT_STICK_UNDEADZONE_INNER, '0.3')
assert.equal(getKeymapValue(projectLayer(folded, ''), 'LEFT_STICK_UNDEADZONE_INNER'), '0.1')
console.log('PASS: virtual-stick compensation, native probe/cutoff, typed validation, mode switching, target isolation, layers, dependencies and unknown config round-trip')

const modes = load('src/utils/sourceModeSettings.ts')
const cycle = load('src/utils/cycleBinding.ts')
const activation = load('src/utils/gyroActivation.ts')
const gyroScope = load('src/utils/gyroSettingsScope.ts')
const scope = load('src/utils/configScopes.ts')
const chorded = 'R,GYRO_OUTPUT = RIGHT_STICK # keep\r\nR,RIGHT_STICK_UNPOWER = 2.3\r\nR,MOTION_STICK_MODE = LEFT_STEER_X\r\nR,UNKNOWN_FUTURE_KEY = untouched\r\nL,GYRO_SENS = 4\r\nL,RIGHT_STICK_UNPOWER = 1.5\r\n'
const retargeted = gyroScope.moveGyroSettingChord(chorded, 'R', 'L')
assert.match(retargeted, /L,GYRO_OUTPUT = RIGHT_STICK # keep\r\n/)
assert.match(retargeted, /R,MOTION_STICK_MODE = LEFT_STEER_X/)
assert.match(retargeted, /R,UNKNOWN_FUTURE_KEY = untouched/)
assert.match(retargeted, /R,RIGHT_STICK_UNPOWER = 2.3/)
assert.match(retargeted, /L,RIGHT_STICK_UNPOWER = 1.5/)
assert.equal(gyroScope.moveGyroSettingChord(chorded, 'R', 'R'), chorded)
const clipboard = scope.scopedConfig(retargeted, gyroScope.GYRO_TUNING_KEYS)
assert.match(clipboard, /L,RIGHT_STICK_UNPOWER = 1.5/)
assert.match(clipboard, /R,MOTION_STICK_MODE = LEFT_STEER_X/)
assert.doesNotMatch(clipboard, /UNKNOWN_FUTURE/)
assert.deepEqual(activation.parseGyroActivation('GYRO_ON = ANY MISC5 MISC6 # grip\n'), { mode: 'hold_on', button: 'ANY MISC5 MISC6' })
assert.deepEqual(activation.gyroConditions('ALL MISC5 !MISC6'), { match: 'ALL', conditions: [{ input: 'MISC5', released: false }, { input: 'MISC6', released: true }] })
assert.equal(activation.gyroConditionValue('ANY', Array(17).fill({input: 'N', released: false})), null)
const activationText = activation.writeGyroActivation('GYRO_ON = MISC5\nR,GYRO_ON = MISC6\n', 'hold_off', 'ALL MISC5 !MISC6', 'R,')
const always = activation.writeGyroActivation('"Inherited profile.txt"\nGYRO_ON = MISC5\n', 'always_on', '')
assert.match(always, /GYRO_OFF = NONE/)
assert.match(always, /"Inherited profile.txt"/)
assert.deepEqual(activation.parseGyroActivation('GYRO_ON = MISC6\n' + always), { mode: 'always_on', button: '' })
assert.deepEqual(activation.parseGyroActivation(activationText, 'R,'), { mode: 'hold_off', button: 'ALL MISC5 !MISC6' })
assert.equal(getKeymapValue(activationText, 'GYRO_ON'), 'MISC5')
assert.match(serializeConfig(parseConfigText(activationText)), /R,GYRO_OFF = ALL MISC5 !MISC6/)
const triggers = load('src/utils/adaptiveTriggers.ts')
for (const mode of Object.keys(triggers.TRIGGER_EFFECTS)) {
  const effect = triggers.defaultTriggerEffect(mode)
  assert.equal(triggers.triggerEffectProblem(effect), null, mode)
  const edited = triggers.writeTriggerEffect('RIGHT_TRIGGER_EFFECT = ON\nLEFT_TRIGGER_EFFECT = OFF # keep\nUNKNOWN = untouched\n', 'LEFT', effect)
  assert.deepEqual(triggers.parseTriggerEffect(getKeymapValue(edited, 'LEFT_TRIGGER_EFFECT')), effect)
  assert.equal(getKeymapValue(edited, 'RIGHT_TRIGGER_EFFECT'), 'ON')
  assert.match(edited, /# keep/)
  assert.match(serializeConfig(parseConfigText(edited)), /UNKNOWN = untouched/)
}
assert.equal(triggers.writeTriggerEffect('LEFT_TRIGGER_EFFECT = OFF\n', 'LEFT', { mode: 'BOW', values: [7, 2, 4, 4] }), 'LEFT_TRIGGER_EFFECT = OFF\n')
assert.equal(triggers.triggerEffectProblem({ mode: 'GALLOPING', values: [2, 8, 6, 2, 20] }), 'The second pulse phase must exceed the first.')
assert.equal(triggers.parseTriggerEffect('FUTURE_MODE 1 2'), null)
assert.equal(triggers.triggerEffectProblem({ mode: 'AUTOMATIC', values: [64, 128, 256] }), 'A parameter is outside the supported effect range.')
const configMacros = load('src/utils/config.ts')
assert.equal(configMacros.osMouseSpeedCompensated('COUNTER_OS_MOUSE_SPEED\nIGNORE_OS_MOUSE_SPEED\n'), false)
assert.equal(configMacros.osMouseSpeedCompensated('IGNORE_OS_MOUSE_SPEED\nCOUNTER_OS_MOUSE_SPEED\n'), true)
assert.match(configMacros.writeOsMouseSpeedCompensation('COUNTER_OS_MOUSE_SPEED\n# keep\n', false), /IGNORE_OS_MOUSE_SPEED/)
console.log('PASS: all adaptive effect encodings, coupled validation, per-side isolation, unknown preservation and mouse-compensation precedence')
const commands = load('src/utils/bindingCommands.ts')
const virtual = load('src/utils/virtualController.ts')
const shifts = load('src/utils/modeshift.ts')
const hybridY = modes.MODE_NUMBERS.HYBRID_AIM[1]
const hybrid = modes.writeModeNumber('MOUSELIKE_FACTOR = 30 45 # preserve\n', hybridY, 60)
assert.match(hybrid, /MOUSELIKE_FACTOR = 30 60 # preserve/)
assert.equal(modes.readModeNumber('MOUSELIKE_FACTOR = 30\n', hybridY), 30, 'single value is both axes')
assert.equal(modes.writeModeNumber('ANGLE_TO_AXIS_DEADZONE_OUTER = 10\n', modes.MODE_NUMBERS.ANGLE[0], 81), 'ANGLE_TO_AXIS_DEADZONE_OUTER = 10\n')
assert.equal(modes.writeModeNumber('', modes.MODE_NUMBERS.WIND[0], 0), '', 'zero winding denominator rejected')
assert.ok(shifts.stickModeshiftSettings('LEFT').includes('WIND_STICK_RANGE'))
assert.ok(shifts.stickModeshiftSettings('RIGHT').includes('RIGHT_STICK_UNPOWER'))
assert.ok(shifts.stickModeshiftSettings('RIGHT').includes('RIGHT_STICK_DEADZONE_PROBE'))
assert.ok(shifts.padModeshiftSettings('LEFT').includes('LEFT_STICK_DEADZONE_PROBE'))
assert.ok(gyroScope.GYRO_TUNING_KEYS.test('RIGHT_STICK_DEADZONE_PROBE'))
const shiftedSource = 'STICK_POWER = 1\nR,RIGHT_STICK_MODE = RIGHT_WIND_X\nR,WIND_STICK_RANGE = 900\n'
const shiftView = shifts.projectModeshift(shiftedSource, 'R')
const shiftNext = modes.writeModeNumber(shiftView, modes.MODE_NUMBERS.WIND[0], 1080)
const shiftFold = shifts.foldModeshift(shiftedSource, 'R', shiftNext, {}, shiftView)
assert.equal(getKeymapValue(shiftFold, 'R,WIND_STICK_RANGE'), '1080')
assert.equal(getKeymapValue(shiftFold, 'WIND_STICK_RANGE'), undefined)
assert.equal(cycle.cycleBinding(['1', '2', '3']), 'CYCLE 1 | 2 | 3')
assert.deepEqual(cycle.parseCycleBinding('CYCLE X_A | X_B'), ['X_A', 'X_B'])
assert.equal(cycle.parseCycleBinding('CYCLE 1 |'), null)
assert.equal(cycle.parseCycleBinding('CYCLE 1 | ^2'), null)
assert.equal(cycle.cycleBinding(Array(33).fill('1')), null)
const cyclePreset = commands.createBindingCommandPreset('regular', { outputKind: 'command', outputValue: cycle.cycleBinding(['X_A', 'X_B']), outputBehavior: 'tapOnce' })
const cycleToken = commands.commandTokenPreview(cyclePreset)
assert.equal(cycleToken, '!"CYCLE X_A | X_B"')
const cycleConfig = 'RESET_MAPPINGS\nN = ' + cycleToken + '\nUNKNOWN = keep\n'
assert.ok(virtual.analyzeVirtualControllerConfig(cycleConfig).warnings.some(warning => warning.kind === 'modeRequired'))
const migrated = virtual.migrateVirtualBindings(cycleConfig, 'DS4')
assert.match(migrated, /CYCLE PS_CROSS \| PS_CIRCLE/)
const cycleSaved = serializeConfig(parseConfigText(migrated))
assert.match(cycleSaved, /!"CYCLE PS_CROSS \| PS_CIRCLE"/)
assert.match(cycleSaved, /UNKNOWN = keep/)
assert.equal(serializeConfig(parseConfigText(cycleSaved)), cycleSaved)
console.log('PASS: curated source defaults, coupled validation, hybrid axis isolation, source modeshifts and cycle syntax/dependencies/migration/round-trip')
