const assert = require('node:assert/strict')
const fs = require('node:fs'), path = require('node:path'), Module = require('node:module')
const app = path.resolve(__dirname, '../JSM_GUI/jsm_gui_tauri')
const ts = require(path.join(app, 'node_modules/typescript')), cache = new Map()
function load(file) {
  file = path.resolve(file)
  if (cache.has(file)) return cache.get(file).exports
  const mod = new Module(file); cache.set(file, mod); mod.filename = file; mod.paths = Module._nodeModulePaths(path.dirname(file))
  mod.require = name => name.startsWith('.') ? load(path.resolve(path.dirname(file), name + '.ts')) : require(name)
  mod._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS } }).outputText, file)
  return mod.exports
}
const d = load(path.join(app, 'src/utils/gyroDeflectionSettings.ts'))
const k = load(path.join(app, 'src/utils/keymap.ts'))
const v = load(path.join(app, 'src/utils/virtualStickSettings.ts'))
const c = load(path.join(app, 'src/utils/configSerializer.ts'))
const l = load(path.join(app, 'src/utils/layers.ts'))
const source = 'RESET_MAPPINGS\nGYRO_OUTPUT = RIGHT_STICK\nGYRO_STICK_DEFLECTION = OFF\nGYRO_DEFLECTION_RANGE = 30 45 # base range\nL,GYRO_STICK_DEFLECTION = ON\nL,GYRO_DEFLECTION_RANGE = 15 20 # ADS range\nGYRO_SENS = 2 3\nUNKNOWN_DEFLECTION = retain exactly\n'
assert.equal(d.gyroDeflectionEnabled(source), false)
assert.equal(d.gyroDeflectionEnabled(source, 'L,'), true)
assert.deepEqual(d.gyroDeflectionRange('GYRO_DEFLECTION_RANGE = 12'), { x: 12, y: 12, problem: null })
for (const value of ['0 20', 'NaN 20', '30 181', '30 40 50']) assert.ok(d.gyroDeflectionRange('GYRO_DEFLECTION_RANGE = ' + value).problem)
let edited = d.writeGyroDeflectionRange(source, source, 'x', 16, 'L,')
assert.match(edited, /L,GYRO_DEFLECTION_RANGE = 16 20 # ADS range/)
assert.match(edited, /^GYRO_DEFLECTION_RANGE = 30 45 # base range$/m)
assert.equal(d.writeGyroDeflectionRange(source, source, 'y', NaN), source)
assert.equal(d.writeGyroDeflectionRange(source, source, 'y', 181), source)
edited = v.writeVirtualSetting(edited, 'GYRO_STICK_DEFLECTION', 'ON')
const saved = c.serializeConfig(c.parseConfigText(edited))
assert.equal(d.gyroDeflectionEnabled(saved), true)
assert.equal(k.getKeymapValue(saved, 'GYRO_SENS'), '2 3')
assert.match(saved, /UNKNOWN_DEFLECTION = retain exactly/)
let layered = l.writeLayers(source, [{ id: 'vehicle', name: 'Vehicle', trigger: 'L', behavior: 'hold', overrides: { GYRO_STICK_DEFLECTION: 'ON', GYRO_DEFLECTION_RANGE: '40 60' } }])
const projected = l.projectLayer(layered, 'vehicle')
const next = d.writeGyroDeflectionRange(projected, projected, 'y', 61)
layered = l.foldLayer(layered, 'vehicle', next, projected)
assert.equal(d.gyroDeflectionRange(l.projectLayer(layered, 'vehicle')).y, 61)
assert.equal(d.gyroDeflectionRange(l.projectLayer(layered, null)).y, 45)
console.log('PASS: angular deflection defaults, scalar/pair native ranges, validation, held and layer isolation, comments, mode retention and saved unknown config')
