// Isolated UI, ordinary config writes and simulated telemetry only.
const assert = require('node:assert/strict')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/luker/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1024, height: 720 } })
    const errors = []; page.on('pageerror', error => errors.push(error.message))
    await page.addInitScript(() => {
      let content = 'RESET_MAPPINGS\nGYRO_OUTPUT = RIGHT_STICK\nVIRTUAL_CONTROLLER = XBOX\nGYRO_STICK_DEFLECTION = OFF\nGYRO_DEFLECTION_RANGE = 30 45 # base travel\nL,GYRO_STICK_DEFLECTION = ON\nL,GYRO_DEFLECTION_RANGE = 15 20 # ADS travel\nGYRO_SENS = 2 3\nUNKNOWN_DEFLECTION = preserve exactly\n'
      window.electronAPI = {
        getActiveProfile: async () => ({ name: 'Deflection', path: 'profiles-library/Deflection.txt', content }),
        listLibraryProfiles: async () => ['Deflection'], loadLibraryProfile: async () => ({ name: 'Deflection', content }),
        readConfigFile: async () => '', getRuntimeMappingState: async () => ({ mappingEnabled: true, firmwareSoundPromptDone: true }),
        saveLibraryProfile: async (name, next) => { content = next; window.__saved = next; return { name } },
        applyProfile: async path => ({ path, mappingEnabled: true }),
      }
      window.telemetry = { onSample: cb => {
        const emit = () => cb({ omega: 12, activeProfile: 'profiles-library/Deflection.txt', devices: [{ handle: 1, type: 24, supportedButtons: 8589934591, status: { buttons: 0, leftStick: { x: 0, y: 0 }, rightStick: { x: 0, y: 0 }, triggers: { left: 0, right: 0 }, gyro: { x: 0, y: 0, z: 0 }, virtualSticks: { left: { x: 0, y: 0 }, right: { x: .2, y: -.1 } } } }] })
        emit(); const timer = setInterval(emit, 100); return () => clearInterval(timer)
      } }
    })
    await page.goto(process.env.JSM_TEST_URL || 'http://127.0.0.1:1421')
    await page.locator('[data-home-continue]').click()
    await page.getByRole('button', { name: 'Gyro', exact: true }).click()
    const row = label => page.locator('button.summary-row').filter({ has: page.locator('.summary-row__label').getByText(label, { exact: true }) }).first()
    await row('Joystick behavior').click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    assert.match(await row('Joystick behavior').innerText(), /Angular deflection/)
    assert.equal(await page.locator('#gyro-sensitivity').count(), 0)
    assert.equal(await row('Maximum game turn rate').count(), 0)
    const horizontal = row('Horizontal rotation for full output')
    await horizontal.click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Escape')
    assert.match(await horizontal.innerText(), /30°/)
    await horizontal.click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    assert.match(await horizontal.innerText(), /31°/)
    await row('Lock deflection limits').click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    assert.match(await row('Lock deflection limits').innerText(), /Off/)
    await row('Noise & Steadying').click()
    assert.equal(await page.getByRole('textbox', { name: /Angle snap/i }).count(), 0)
    await page.keyboard.press('Escape')
    await row('Noise & Steadying').click()
    const smooth = page.getByRole('textbox', { name: 'Smoothing time', exact: true })
    assert.equal(await smooth.inputValue(), '', 'native default remains implicit')
    assert.equal(await smooth.getAttribute('placeholder'), '0.125')
    assert.equal(await page.getByRole('slider', { name: 'Smoothing time', exact: true }).getAttribute('aria-valuenow'), '0.125')
    await smooth.fill('0.125'); await smooth.press('Enter')
    for (const [name, value] of [['Smoothing threshold', '75'], ['Cutoff speed', '12'], ['Steadying', '20']]) {
      const input = page.getByRole('textbox', { name, exact: true })
      await input.fill(value); await input.press('Enter'); assert.equal(await input.inputValue(), value)
    }
    await page.keyboard.press('Escape')
    await page.getByRole('combobox', { name: 'Held settings', exact: true }).click()
    await page.getByRole('option').filter({ has: page.locator('[data-glyph="L"]') }).click()
    await page.getByRole('button', { name: 'While shifted', exact: true }).click()
    assert.match(await horizontal.innerText(), /15°/)
    await horizontal.click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    assert.match(await horizontal.innerText(), /16°/)
    await row('Noise & Steadying').click()
    await smooth.waitFor()
    await page.waitForFunction(() => [...document.querySelectorAll('input')].some(input => input.getAttribute('aria-label') === 'Smoothing time' && input.value === '0.125'))
    await smooth.fill('0.25'); await smooth.press('Enter')
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Base values', exact: true }).click()
    assert.match(await horizontal.innerText(), /31°/)
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => /GYRO_DEFLECTION_RANGE = 31 45/.test(window.__saved || ''))
    const saved = await page.evaluate(() => window.__saved)
    assert.match(saved, /^GYRO_STICK_DEFLECTION = ON$/m)
    assert.match(saved, /^GYRO_DEFLECTION_RANGE = 31 45 # base travel$/m)
    assert.match(saved, /^L,GYRO_DEFLECTION_RANGE = 16 20 # ADS travel$/m)
    assert.match(saved, /^GYRO_DEFLECTION_LOCK_EXTENTS = OFF$/m)
    assert.match(saved, /^GYRO_SENS = 2 3$/m)
    assert.match(saved, /^GYRO_SMOOTH_TIME = 0.125$/m)
    assert.match(saved, /^L,GYRO_SMOOTH_TIME = 0.25$/m)
    assert.match(saved, /^GYRO_SMOOTH_THRESHOLD = 75$/m)
    assert.match(saved, /^GYRO_CUTOFF_SPEED = 12$/m)
    assert.match(saved, /^GYRO_CUTOFF_RECOVERY = 20$/m)
    assert.match(saved, /UNKNOWN_DEFLECTION = preserve exactly/)
    await horizontal.scrollIntoViewIfNeeded()
    await page.screenshot({ path: 'tmp/parity-verification/gyro-angular-deflection-controls.png' })
    await page.locator('[data-virtual-stick] figure').scrollIntoViewIfNeeded()
    await page.screenshot({ path: 'tmp/parity-verification/gyro-angular-deflection-correction.png' })
    await row('Joystick behavior').click(); await page.keyboard.press('ArrowLeft'); await page.keyboard.press('Enter')
    assert.equal(await page.locator('#gyro-sensitivity').count(), 1, 'camera sensitivity returns when applicable')
    assert.equal(await horizontal.count(), 0)
    await page.getByRole('button', { name: 'Buttons', exact: true }).click()
    const input = page.locator('details[data-input-command="S"]').first()
    await input.locator(':scope > summary').click()
    await input.getByRole('button', { name: 'Add command', exact: true }).click()
    const picker = page.getByRole('dialog', { name: 'Choose an action' })
    await picker.locator('.action-tab', { hasText: /^JSM$/ }).click()
    await picker.getByRole('button', { name: 'Recenter gyro deflection', exact: true }).click()
    await input.getByText('Recenter gyro deflection', { exact: true }).waitFor()
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => /S = .*RECENTER_GYRO_DEFLECTION/.test(window.__saved || ''))
    assert.match(await page.evaluate(() => window.__saved), /^S = "RECENTER_GYRO_DEFLECTION"$/m)
    assert.deepEqual(errors, [])
    console.log('PASS: deflection mode-dependent controls, cancellation, held range edit, comments, latent camera gain and saved ordinary configuration')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
