const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('../JSM_GUI/jsm_gui_tauri/node_modules/typescript');
const cache = new Map();
function load(file) {
  file = path.resolve(file);
  if (cache.has(file)) return cache.get(file).exports;
  const mod = new Module(file); cache.set(file, mod);
  mod.filename = file; mod.paths = Module._nodeModulePaths(path.dirname(file));
  mod.require = name => name.startsWith('.') ? load(path.resolve(path.dirname(file), name + '.ts')) : require(name);
  mod._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), {compilerOptions: {module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020}}).outputText, file);
  return mod.exports;
}
const {addModeshift, readModeshift, writeModeshift, renameModeshift, removeModeshift, modeshiftTriggers} = load('JSM_GUI/jsm_gui_tauri/src/utils/modeshift.ts');
const face = {id:'face',title:'Face buttons',buttons:['N','S','E','W'].map(command=>({command,label:command}))};
const pad = {id:'right-pad',title:'Right trackpad',buttons:Array.from({length:25},(_,i)=>({command:`RT${i+1}`,label:`RT${i+1}`})),settings:['RIGHT_GRID_SIZE','RIGHT_GRID_REQUIRES_CLICK','RIGHT_TOUCH_STICK_MODE'],mode:{key:'RIGHT_TOUCHPAD_MODE',defaultValue:'GRID_AND_STICK'},grid:{sizeKey:'RIGHT_GRID_SIZE',clickKey:'RIGHT_GRID_REQUIRES_CLICK',stickKey:'RIGHT_TOUCH_STICK_MODE'}};
const original = '# retain me\nN = SPACE\nRIGHT_TOUCHPAD_MODE = MOUSE\nRIGHT_GRID_SIZE = 2 1\nRT1 = ENTER\n';
assert.equal(addModeshift(original,pad,''), original, 'empty trigger must not create a shift');
assert.throws(()=>writeModeshift(original,'','N','TAB'));
let text = addModeshift(original,pad,'MISC2');
text = writeModeshift(text,'MISC2','RIGHT_GRID_SIZE','3 2');
text = writeModeshift(text,'MISC2','RT6','ESC');
assert.equal(readModeshift(text,'MISC2','RIGHT_GRID_REQUIRES_CLICK'),'OFF');
assert.equal(readModeshift(text,'MISC2','RIGHT_TOUCH_STICK_MODE'),'NO_MOUSE');
assert.equal(readModeshift(text,'MISC2','RT1'),'ENTER', 'legacy grid binding retained in alternate card');
assert.ok(text.includes('RIGHT_TOUCHPAD_MODE = MOUSE\nRIGHT_GRID_SIZE = 2 1'), 'normal mode and grid unchanged');
text = addModeshift(text,face,'MISC2');
text = writeModeshift(text,'MISC2','N','TAB');
assert.equal(readModeshift(text,'MISC2','N'),'TAB');
text = addModeshift(text,pad,'L');
assert.deepEqual(modeshiftTriggers(text,pad), ['MISC2','L']);
assert.equal(renameModeshift(text,pad,'MISC2','L'),text,'cannot overwrite an existing trigger');
text = renameModeshift(text,pad,'MISC2','R');
assert.equal(readModeshift(text,'R','RT6'),'ESC');
assert.equal(readModeshift(text,'MISC2','N'),'TAB','renaming pad shift preserves face shift on same trigger');
text = removeModeshift(text,pad,'R');
assert.equal(readModeshift(text,'R','RT6'),undefined);
assert.equal(readModeshift(text,'L','RT1'),'ENTER');
assert.equal(readModeshift(text,'MISC2','N'),'TAB');
assert.ok(text.includes('# retain me'));
const spaced = '  misc2 , RIGHT_GRID_SIZE=2 2 # old\nMISC2,RIGHT_GRID_SIZE = 4 1\n';
assert.equal(readModeshift(spaced,'MISC2','RIGHT_GRID_SIZE'),'4 1');
assert.equal(writeModeshift(spaced,'MISC2','RIGHT_GRID_SIZE','3 3').match(/RIGHT_GRID_SIZE/g).length,1);
console.log('PASS: mandatory triggers, independent normal/alternate layouts, legacy bindings, multiple shifts, scoped rename/remove and whitespace handling');
