// Native settings UI, isolated renderer. Does not start a mapper or touch hardware.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/luker/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
    page.setDefaultTimeout(12000)
    const errors = []; page.on('pageerror', error => errors.push(error.message))
    await page.addInitScript(() => {
      let content = 'RESET_MAPPINGS\nGYRO_ON = MISC5\nZL_MODE = PS_L2\nZR_MODE = MAY_SKIP_R\nTRIGGER_THRESHOLD = 0.1 # calibrated travel\nTRIGGER_HYSTERESIS = 0.4 # measured guard\nLEFT_TRIGGER_EFFECT = RESISTANCE 2 4 # measured\nRIGHT_TRIGGER_EFFECT = BOW 2 7 4 5\nUNKNOWN_PARITY_SETTING = untouched\n'
      window.electronAPI = {
        getActiveProfile: async () => ({ name: 'Parity', path: 'profiles-library/Parity.txt', content }),
        listLibraryProfiles: async () => ['Parity'], loadLibraryProfile: async () => ({ name: 'Parity', content }),
        readConfigFile: async () => '', getRuntimeMappingState: async () => ({ mappingEnabled: true, firmwareSoundPromptDone: true }),
        saveLibraryProfile: async (name, next) => { content = next; window.__paritySaved = next; return { name } }, applyProfile: async path => ({ path, mappingEnabled: true }),
      }
      window.telemetry = { onSample: callback => {
        const emit = () => callback({ activeProfile: 'profiles-library/Parity.txt', devices: [{ handle: 1, type: 5, status: { buttons: 0, leftStick: { x: 0, y: 0 }, rightStick: { x: 0, y: 0 }, triggers: { left: 0, right: 0 }, gyro: { x: 0, y: 0, z: 0 } } }] })
        emit(); const timer = setInterval(emit, 100); return () => clearInterval(timer)
      } }
    })
    await page.goto(process.env.JSM_TEST_URL || 'http://127.0.0.1:1421')
    await page.getByRole('button', { name: 'Keep them', exact: true }).click({ timeout: 5000 }).catch(() => {})
    await page.locator('[data-home-continue]').click()
    const row = (label, scope = page) => scope.locator('button.summary-row').filter({ has: page.locator('.summary-row__label').getByText(label, { exact: true }) })
    // Gyro (console v2, P5): When is gyro on? combines inputs; Tilt ▸ Orientation has the mounting direction.
    await page.locator('button.page-tab').filter({ hasText: /^Gyro$/ }).click()
    await page.locator('[data-gyro-front]').waitFor()
    await page.locator('[data-gyro-front] section').first().locator('button').last().click()
    const whenOn = page.locator('[data-subpage]').last()
    await whenOn.locator('[data-add-condition]').click()
    await page.getByRole('dialog').last().locator('[data-hold-input="L"]').focus()
    await page.keyboard.press('Enter')
    const countIt = whenOn.locator('[role="radiogroup"]').filter({ hasText: /^Count it when/ })
    await countIt.locator('button').filter({ hasText: /^All of them$/ }).click()
    const second = whenOn.locator('[data-condition="1"]')
    await second.focus(); await page.keyboard.press('ArrowRight')
    assert.match(await second.innerText(), /Let go/)
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => /GYRO_ON = ALL MISC5 !L/.test(window.__paritySaved || ''))
    await page.keyboard.press('Escape')
    // The front names it, and the single-input choice is gone: it's a combined condition now.
    assert.match(await page.locator('[data-gyro-front] [data-q1="hold"]').innerText(), /All of 2 inputs/)
    await page.locator('[data-gyro-fine-tune]').click()
    await page.locator('[data-subpage] button[data-group="direction"]').click()
    await page.locator('[data-subpage] button').filter({ hasText: /^AdvancedTilt/ }).first().click()
    await page.locator('[data-subpage] button').filter({ hasText: /^TiltWhat tilting does/ }).first().click()
    await page.locator('[data-subpage] nav[aria-label="Groups"] button').filter({ hasText: /^Orientation/ }).click()
    const mounting = page.locator('[data-subpage] [role="radiogroup"]').filter({ hasText: /^Controller mounting direction/ })
    await mounting.focus()
    for (let index = 0; index < 4; index++) await page.keyboard.press('ArrowRight')
    assert.equal(await mounting.locator('button[data-current="true"]').innerText(), 'Sideways Joy-Con pair')
    assert.doesNotMatch(await mounting.innerText(), /joycon_sideways/i)
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => /CONTROLLER_ORIENTATION = JOYCON_SIDEWAYS/.test(window.__paritySaved || ''))
    for (let index = 0; index < 3; index++) await page.keyboard.press('Escape')
    // Triggers (console v2, P4): one trigger at a time on the rail; press points,
    // resistance and Sends as live in Fine-tune and its Advanced.
    await page.getByRole('button', { name: 'Triggers', exact: true }).click()
    const leftTrigger = page.locator('#trigger-left')
    await leftTrigger.waitFor()
    assert.equal(await leftTrigger.locator('[role="radio"][data-current="true"]').getAttribute('data-value'), 'GAMEPAD', 'PlayStation analogue alias is the Gamepad trigger card')
    assert.match(await leftTrigger.innerText(), /press points aren’t used while Gamepad trigger is chosen/, 'and the page says its digital tuning is unused')
    await page.locator('.section-item').filter({ hasText: 'Right trigger' }).click()
    const rightTrigger = page.locator('#trigger-right')
    await rightTrigger.waitFor()
    assert.equal(await rightTrigger.locator('[role="radio"][data-current="true"]').getAttribute('data-value'), 'MAY_SKIP_R')
    assert.match(await rightTrigger.locator('[role="radio"][data-current="true"]').innerText(), /Half at once, full adds on/)
    await rightTrigger.locator('[data-trigger-fine-tune]').click()
    const sub = page.locator('[data-subpage]').last()
    const slider = label => sub.locator('[role="slider"]').filter({ hasText: label })
    const guard = slider('Release margin')
    assert.equal(await guard.getAttribute('aria-valuetext'), '40%')
    await guard.focus(); await page.keyboard.press('ArrowRight')
    assert.equal(await guard.getAttribute('aria-valuetext'), '40.5%')
    fs.mkdirSync(path.resolve(__dirname, '../tmp/parity-verification'), { recursive: true })
    await sub.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/trigger-digital-controls.png') })
    const detection = sub.locator('[role="radiogroup"][aria-label="Fires at"]')
    await detection.focus(); await page.keyboard.press('ArrowRight')
    assert.equal(await guard.getAttribute('aria-disabled'), 'true', 'hair trigger leaves the fixed-threshold guard unused')
    await sub.getByText('A hair trigger needs push-back off on a DualSense. While push-back is on, it fires at 0% instead.', { exact: true }).waitFor()
    await sub.locator('button').filter({ hasText: 'Use hair trigger without push-back' }).click()
    await detection.focus(); await page.keyboard.press('ArrowLeft')
    assert.equal(await guard.getAttribute('aria-valuetext'), '40.5%', 'switching detection preserves latent guard tuning')
    // Resistance: each trigger's own effect.
    await sub.locator('[data-group="resistance"]').click()
    const effectSide = sub.locator('[role="radiogroup"][aria-label="Trigger"]')
    assert.equal(await sub.locator('[role="radio"][data-current="true"]').getAttribute('data-value'), 'BOW', 'the right trigger keeps its Bow')
    const snap = slider('Snap strength')
    assert.equal(await snap.getAttribute('aria-valuenow'), '5', 'its snap strength reads as written')
    await effectSide.focus(); await page.keyboard.press('ArrowLeft')
    assert.equal(await sub.locator('[role="radio"][data-current="true"]').getAttribute('data-value'), 'RESISTANCE')
    const strength = slider('Strength')
    await strength.focus(); await page.keyboard.press('ArrowRight')
    assert.equal(await strength.getAttribute('aria-valuenow'), '5')
    await page.keyboard.press('Escape')
    await page.locator('[data-subpage]').waitFor({ state: 'detached' })
    // The left trigger's Gamepad trigger sends as the right pad trigger (Advanced ▸ Sends as).
    await page.locator('.section-item').filter({ hasText: 'Left trigger' }).click()
    await leftTrigger.locator('[data-trigger-fine-tune]').click()
    await page.locator('[data-subpage] button').filter({ hasText: 'Quick full press window' }).click()
    const sendsAs = page.locator('[data-subpage]').last().locator('[role="radiogroup"][aria-label="Sends as"]')
    await sendsAs.focus(); await page.keyboard.press('ArrowRight')
    await page.keyboard.press('Escape')
    const press = page.locator('[data-subpage]').last()
    await press.locator('[role="radiogroup"][aria-label="Fires at"]').focus(); await page.keyboard.press('ArrowRight')
    assert.equal(await press.locator('[role="slider"]').filter({ hasText: 'Half-press point' }).getAttribute('aria-disabled'), 'true', 'a hair trigger has no set point')
    await page.keyboard.press('Escape')
    await page.locator('[data-subpage]').waitFor({ state: 'detached' })
    await page.getByRole('button', { name: 'Buttons', exact: true }).click()
    // Cycle (console v2, BindingFineTune): chosen as a Controller action; its steps are
    // edited in Fine-tune's Only for some actions ▸ Cycle through keys.
    const card = page.locator('details[data-input-command="N"]').first()
    await card.locator(':scope > summary').click()
    const sheet = page.locator('details[data-input-command="N"][open] [data-binding-sheet]')
    await sheet.locator('[data-kind="controller"]').first().click()
    const picker = page.locator('[data-picker="controller"]')
    await picker.locator('[data-category="other"]').click()
    await picker.locator('[data-action="CYCLE"]').click()
    // The tile opens the cycle's own page (UX review 2026-10-09, L7): the steps, then Add.
    const cyclePage = page.locator('[data-picker="cycle"]')
    await cyclePage.waitFor()
    assert.equal(await cyclePage.locator('button[aria-label^="Step "]').count(), 3, 'the page starts with the three default steps')
    await cyclePage.locator('[data-param-use]').click()
    await cyclePage.waitFor({ state: 'detached' })
    await picker.waitFor({ state: 'detached' })
    await sheet.locator('[data-fold="fine-tune"]').click()
    const editor = page.locator('[data-cycle-editor="true"]')
    await editor.waitFor()
    const steps = editor.locator('button[aria-label^="Step "]')
    assert.equal(await steps.count(), 3)
    await editor.getByRole('button', { name: '+ Step' }).click()
    // Adding opens that step's picker; leave it as it came (a copy of the last).
    await page.getByRole('dialog', { name: 'Choose an action' }).waitFor()
    await page.keyboard.press('Escape')
    await page.getByRole('dialog', { name: 'Choose an action' }).waitFor({ state: 'detached' })
    assert.equal(await steps.count(), 4)
    const stepMenu = async (index, item) => {
      await steps.nth(index).focus()
      await page.keyboard.press('y')
      await page.getByRole('menuitem', { name: item, exact: true }).click()
    }
    await stepMenu(3, 'Move earlier')
    await stepMenu(0, 'Remove this step')
    assert.equal(await steps.count(), 3)
    await steps.first().click()
    // Nested editors keep the Search every action catalogue, restricted to keys, mouse and pad buttons.
    const nested = page.getByRole('dialog', { name: 'Choose an action' })
    assert.equal(await nested.locator('.action-tab').filter({ hasText: /^Controller action$/ }).count(), 0, 'cycle cannot contain nested commands')
    await nested.locator('.action-tab').filter({ hasText: /^Keyboard key$/ }).click(); await nested.locator('.action-group-tab').filter({ hasText: /^Full keyboard/ }).click()
    await nested.locator('.key-cap[data-token="4"]').click()

    await page.keyboard.press('Escape')
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => !!window.__paritySaved)
    const saved = await page.evaluate(() => window.__paritySaved)
    assert.match(saved, /GYRO_ON = ALL MISC5 !L/)
    assert.match(saved, /CONTROLLER_ORIENTATION = JOYCON_SIDEWAYS/)
    assert.match(saved, /LEFT_TRIGGER_EFFECT = RESISTANCE 2 5 # measured/)
    assert.match(saved, /ZL_MODE = X_RT/)
    assert.match(saved, /TRIGGER_HYSTERESIS = 0.405 # measured guard/)
    assert.match(saved, /ADAPTIVE_TRIGGER = OFF/)
    assert.match(saved, /TRIGGER_THRESHOLD = -1 # calibrated travel/)
    assert.match(saved, /RIGHT_TRIGGER_EFFECT = BOW 2 7 4 5/)
    assert.match(saved, /CYCLE 4 \| 3 \| 3/)
    assert.match(saved, /UNKNOWN_PARITY_SETTING = untouched/)
    assert.deepEqual(errors, [])
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/parity-binding-controls.png') })
    console.log('PASS: native Any/All/released gyro conditions, independent adaptive trigger controls, cancel, Cycle editor add/reorder/remove/change, scoped picker and ordinary config save')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exit(1) })
