// Native settings UI, isolated renderer. Does not start a mapper or touch hardware.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/luker/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
    page.setDefaultTimeout(12000)
    const errors = []; page.on('pageerror', error => errors.push(error.message))
    await page.addInitScript(() => {
      let content = 'RESET_MAPPINGS\nGYRO_ON = MISC5\nZL_MODE = PS_L2\nZR_MODE = MAY_SKIP_R\nTRIGGER_THRESHOLD = 0.1 # calibrated travel\nTRIGGER_HYSTERESIS = 0.4 # measured guard\nLEFT_TRIGGER_EFFECT = RESISTANCE 2 4 # measured\nRIGHT_TRIGGER_EFFECT = BOW 2 7 4 5\nUNKNOWN_PARITY_SETTING = untouched\n'
      window.electronAPI = {
        getActiveProfile: async () => ({ name: 'Parity', path: 'profiles-library/Parity.txt', content }),
        listLibraryProfiles: async () => ['Parity'], loadLibraryProfile: async () => ({ name: 'Parity', content }),
        readConfigFile: async () => '', getRuntimeMappingState: async () => ({ mappingEnabled: true, firmwareSoundPromptDone: true }),
        saveLibraryProfile: async (name, next) => { content = next; window.__paritySaved = next; return { name } }, applyProfile: async path => ({ path, mappingEnabled: true }),
      }
      window.telemetry = { onSample: callback => {
        const emit = () => callback({ activeProfile: 'profiles-library/Parity.txt', devices: [{ handle: 1, type: 5, status: { buttons: 0, leftStick: { x: 0, y: 0 }, rightStick: { x: 0, y: 0 }, triggers: { left: 0, right: 0 }, gyro: { x: 0, y: 0, z: 0 } } }] })
        emit(); const timer = setInterval(emit, 100); return () => clearInterval(timer)
      } }
    })
    await page.goto(process.env.JSM_TEST_URL || 'http://127.0.0.1:1421')
    await page.locator('[data-home-continue]').click()
    const row = (label, scope = page) => scope.locator('button.summary-row').filter({ has: page.locator('.summary-row__label').getByText(label, { exact: true }) })
    await page.getByRole('button', { name: 'Gyro', exact: true }).click()
    await row('Activation conditions').click()
    await row('Use several inputs').click()
    await row('Conditions required').click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    await row('Condition 2 matches while').click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    assert.equal(await page.getByRole('combobox', { name: 'Activation input', exact: true }).count(), 0)
    await row('Motion orientation and response').click()
    await row('Controller mounting direction').click()
    for (let index = 0; index < 4; index++) await page.keyboard.press('ArrowRight')
    await page.keyboard.press('Enter')
    assert.match(await row('Controller mounting direction').innerText(), /Sideways Joy-Con pair/)
    assert.doesNotMatch(await row('Controller mounting direction').innerText(), /joycon_sideways/i)
    await page.getByRole('button', { name: 'Triggers', exact: true }).click()
    const leftTrigger = page.locator('#trigger-left')
    const rightTrigger = page.locator('#trigger-right')
    assert.equal(await leftTrigger.getByText('Threshold & release', { exact: true }).count(), 0, 'PlayStation analogue alias hides digital tuning')
    assert.match(await rightTrigger.innerText(), /Soft pull activates immediately/)
    await rightTrigger.getByText('Threshold & release', { exact: true }).click()
    const guard = row('Flicker guard', rightTrigger)
    assert.match(await guard.innerText(), /40%/)
    await guard.click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    assert.match(await guard.innerText(), /40.5%/)
    await rightTrigger.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/trigger-digital-controls.png') })
    const detection = row('Soft pull detection', rightTrigger)
    await detection.click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    assert.equal(await guard.count(), 0, 'hair trigger hides the unused fixed-threshold guard')
    await page.getByText('Hair trigger requires adaptive resistance to be off on DualSense. Until then, JSM uses a travel threshold of zero.', { exact: true }).waitFor()
    await row('Use hair trigger without resistance', rightTrigger).click()
    await detection.click(); await page.keyboard.press('ArrowLeft'); await page.keyboard.press('Enter')
    assert.match(await guard.innerText(), /40.5%/, 'switching detection preserves latent guard tuning')
    await leftTrigger.getByRole('combobox').click()
    await page.getByRole('option', { name: 'Virtual Controller – Analog Trigger · Right', exact: true }).click()
    await detection.click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    assert.match(await detection.innerText(), /Hair trigger/)
    await row('Left adaptive effect').click()
    await row('Strength').click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    await row('Left adaptive effect').click()
    await row('Right adaptive effect').click()
    assert.match(await row('Effect').innerText(), /Bow/)
    await row('Snap strength').click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Escape')
    assert.match(await row('Snap strength').innerText(), /5/)
    await page.getByRole('button', { name: 'Buttons', exact: true }).click()
    const card = page.locator('details[data-input-command="N"]').first()
    await card.locator(':scope > summary').click()
    await card.getByRole('button', { name: 'Add command', exact: true }).click()
    const picker = page.getByRole('dialog', { name: 'Choose an action' })
    await picker.locator('.action-tab').filter({ hasText: /^JSM$/ }).click()
    await picker.getByRole('button', { name: 'Cycle actions', exact: true }).click()
    const editor = page.locator('[data-cycle-editor="true"]')
    await editor.waitFor()
    assert.equal(await editor.getByRole('button', { name: /^Step \d/ }).count(), 3)
    await row('Add cycle step', editor).click()
    await editor.getByRole('button', { name: 'Move step 4 earlier', exact: true }).click()
    await editor.getByRole('button', { name: 'Remove step 1', exact: true }).click()
    await row('Step 1', editor).click()
    const nested = page.getByRole('dialog', { name: 'Choose an action' })
    assert.equal(await nested.locator('.action-tab').filter({ hasText: /^JSM$/ }).count(), 0, 'cycle cannot contain nested commands')
    await nested.locator('.action-tab').filter({ hasText: /^Keyboard$/ }).click()
    await nested.locator('.key-cap[title="4"]').click()
    await page.keyboard.press('Escape')
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => !!window.__paritySaved)
    const saved = await page.evaluate(() => window.__paritySaved)
    assert.match(saved, /GYRO_ON = ALL MISC5 !MISC6/)
    assert.match(saved, /CONTROLLER_ORIENTATION = JOYCON_SIDEWAYS/)
    assert.match(saved, /LEFT_TRIGGER_EFFECT = RESISTANCE 2 5 # measured/)
    assert.match(saved, /ZL_MODE = X_RT/)
    assert.match(saved, /TRIGGER_HYSTERESIS = 0.405 # measured guard/)
    assert.match(saved, /ADAPTIVE_TRIGGER = OFF/)
    assert.match(saved, /TRIGGER_THRESHOLD = -1 # calibrated travel/)
    assert.match(saved, /RIGHT_TRIGGER_EFFECT = BOW 2 7 4 5/)
    assert.match(saved, /CYCLE 4 \| 3 \| 3/)
    assert.match(saved, /UNKNOWN_PARITY_SETTING = untouched/)
    assert.deepEqual(errors, [])
    fs.mkdirSync(path.resolve(__dirname, '../tmp/parity-verification'), { recursive: true })
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/parity-binding-controls.png') })
    console.log('PASS: native Any/All/released gyro conditions, independent adaptive trigger controls, cancel, Cycle editor add/reorder/remove/change, scoped picker and ordinary config save')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exit(1) })
