const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '../JSM_GUI/jsm_gui_tauri')
const ts = require(path.join(root, 'node_modules/typescript'))
const cache = new Map()
function load(file) {
  file = path.resolve(root, file)
  if (cache.has(file)) return cache.get(file)
  const module = { exports: {} }
  const code = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText
  new Function('module', 'exports', 'require', code)(module, module.exports, name => name.startsWith('.') ? load(path.resolve(path.dirname(file), name) + '.ts') : require(name))
  cache.set(file, module.exports)
  return module.exports
}
const a = load('src/utils/gyroActivation.ts')
const s = load('src/utils/configSerializer.ts')
const scope = load('src/utils/gyroSettingsScope.ts')
const shifts = load('src/utils/modeshift.ts')
const source = 'RESET_MAPPINGS\nGYRO_ON = MISC6 # gyro remains independent\nTILT_OFF = R3\nTILT_ON = MISC5 # latest wins\nR,TILT_OFF = NONE\nR,GYRO_ON = NONE\nMOTION_STICK_MODE = LEFT_STEER_X\nMLEFT = A\nUNKNOWN_FUTURE_SETTING = keep # preserve\n'
assert.deepEqual(a.parseTiltActivation(source), { mode: 'hold_on', button: 'MISC5' })
assert.deepEqual(a.parseTiltActivation(source, 'R,'), { mode: 'always_on', button: '' })
assert.deepEqual(a.parseTiltActivation(source, 'L,'), { mode: 'hold_on', button: 'MISC5' })
let text = a.writeTiltActivation(source, 'always_off', '')
assert.equal((text.match(/^TILT_(ON|OFF) =/gm) || []).length, 1)
assert.match(text, /^TILT_ON = NONE$/m)
assert.match(text, /^GYRO_ON = MISC6 # gyro remains independent$/m)
assert.match(text, /^R,TILT_OFF = NONE$/m)
assert.match(text, /^MLEFT = A$/m)
assert.deepEqual(a.parseTiltActivation(text), { mode: 'always_off', button: '' })
text = a.writeTiltActivation(text, 'hold_off', 'ALL MISC5 !MISC6', 'R,')
assert.deepEqual(a.parseTiltActivation(text, 'R,'), { mode: 'hold_off', button: 'ALL MISC5 !MISC6' })
assert.deepEqual(a.parseGyroActivation(text, 'R,'), { mode: 'always_off', button: '' })
text = s.serializeConfig(s.parseConfigText(text))
assert.match(text, /^TILT_ON = NONE$/m)
assert.match(text, /^R,TILT_OFF = ALL MISC5 !MISC6$/m)
assert.match(text, /UNKNOWN_FUTURE_SETTING = keep # preserve/)
assert.equal(s.serializeConfig(s.parseConfigText(text)), text)
const moved = scope.moveGyroSettingChord(text, 'R', 'L')
assert.match(moved, /^R,TILT_OFF = ALL MISC5 !MISC6$/m)
assert.match(moved, /^L,GYRO_ON = NONE$/m)
const projected = shifts.projectModeshift(text, 'R')
assert.deepEqual(a.parseTiltActivation(projected), { mode: 'hold_off', button: 'ALL MISC5 !MISC6' })
const folded = shifts.foldModeshift(text, 'R', a.writeTiltActivation(projected, 'always_on', ''), {}, projected)
assert.match(folded, /^R,TILT_OFF = NONE$/m)
assert.match(folded, /^TILT_ON = NONE$/m)
assert.deepEqual(a.parseTiltActivation('GYRO_ON = NONE\nNO_GYRO_BUTTON\nTILT_ON = R3\n'), { mode: 'hold_on', button: 'R3' })

const gyroTarget = { id: 'gyro', title: 'Gyro', buttons: [], mode: { key: 'GYRO_OUTPUT', defaultValue: 'MOUSE', options: [] }, settings: ['GYRO_ON', 'GYRO_SENS', 'GYRO_DEFLECTION_RANGE', 'RIGHT_STICK_UNPOWER'] }
const tiltTarget = { id: 'tilt', title: 'Tilt', buttons: [], mode: { key: 'MOTION_STICK_MODE', defaultValue: 'NO_MOUSE', options: [] }, settings: ['TILT_ON', 'TILT_OFF', 'MOTION_DEADZONE_INNER', 'STICK_SENS', 'RIGHT_STICK_UNPOWER'] }
for (const key of ['TILT_ON', 'TILT_OFF', 'MOTION_STICK_MODE', 'MOTION_DEADZONE_INNER', 'LEAN_THRESHOLD', 'JOYCON_MOTION_MASK']) {
  assert.equal(scope.isGyroModeshiftKey(key), false)
  assert.equal(scope.TILT_MODESHIFT_KEYS.test(key), true)
}
for (const key of ['GYRO_OUTPUT', 'GYRO_ON', 'GYRO_SENS', 'GYRO_DEFLECTION_RANGE', 'JOYCON_GYRO_MASK']) {
  assert.equal(scope.isGyroModeshiftKey(key), true)
  assert.equal(scope.TILT_MODESHIFT_KEYS.test(key), false)
}
const independent = 'GYRO_OUTPUT = MOUSE\nGYRO_SENS = 2 3\nMOTION_STICK_MODE = NO_MOUSE\nR,GYRO_OUTPUT = RIGHT_STICK\nR,GYRO_SENS = 4 5 # retain gyro\nR,RIGHT_STICK_UNPOWER = 2\n'
let split = shifts.addModeshift(independent, tiltTarget, 'R')
split = shifts.writeModeshift(split, 'R', 'MOTION_STICK_MODE', 'LEFT_STEER_X')
split = a.writeTiltActivation(split, 'always_off', '', 'R,')
assert.deepEqual(shifts.modeshiftTriggers(split, gyroTarget), ['R'])
assert.deepEqual(shifts.modeshiftTriggers(split, tiltTarget), ['R'])
const renamedTilt = shifts.renameModeshift(split, tiltTarget, 'R', 'L')
assert.match(renamedTilt, /^L,MOTION_STICK_MODE = LEFT_STEER_X$/m)
assert.match(renamedTilt, /^R,GYRO_SENS = 4 5 # retain gyro$/m)
assert.match(renamedTilt, /^R,RIGHT_STICK_UNPOWER = 2$/m)
assert.match(renamedTilt, /^L,RIGHT_STICK_UNPOWER = 2$/m)
const removedTilt = shifts.removeModeshift(split, tiltTarget, 'R')
assert.deepEqual(shifts.modeshiftTriggers(removedTilt, tiltTarget), [])
assert.match(removedTilt, /^R,GYRO_SENS = 4 5 # retain gyro$/m)
assert.match(removedTilt, /^R,RIGHT_STICK_UNPOWER = 2$/m)
const removedGyro = shifts.removeModeshift(split, gyroTarget, 'R')
assert.match(removedGyro, /^R,MOTION_STICK_MODE = LEFT_STEER_X$/m)
assert.match(removedGyro, /^R,TILT_ON = NONE$/m)
assert.match(removedGyro, /^R,RIGHT_STICK_UNPOWER = 2$/m)
assert.deepEqual(shifts.modeshiftTriggers(shifts.addModeshift('GYRO_SENS = 2 3', tiltTarget, 'L'), gyroTarget), [])
const movedGyro = scope.moveGyroSettingChord(split, 'R', 'L')
assert.match(movedGyro, /^R,MOTION_STICK_MODE = LEFT_STEER_X$/m)
assert.match(movedGyro, /^R,RIGHT_STICK_UNPOWER = 2$/m)
assert.match(movedGyro, /^L,RIGHT_STICK_UNPOWER = 2$/m)
assert.match(movedGyro, /^L,GYRO_SENS = 4 5 # retain gyro$/m)
console.log('PASS: independent gyro/tilt activation, last-wins parsing, comments, scoped edits, Any/All, serializer and held-setting round trips')
