// Isolated renderer: saved placement only; no physical controller output.
const assert = require('node:assert/strict')
const path = require('node:path')
const fs = require('node:fs')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/luker/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } })
    page.setDefaultTimeout(12000)
    const errors = []; page.on('pageerror', error => errors.push(error.message))
    await page.addInitScript(() => {
      document.hasFocus = () => true
      for (const [key, value] of Object.entries({ width: 2560, availWidth: 2560, height: 1440, availHeight: 1440 })) Object.defineProperty(window.screen, key, { value, configurable: true })
      let content = localStorage.getItem('__positionProfile') || 'RESET_MAPPINGS\n'
      window.electronAPI = {
        getActiveProfile: async () => ({ name: 'Position test', path: 'profiles-library/Position test.txt', content }),
        listLibraryProfiles: async () => ['Position test'], loadLibraryProfile: async () => ({ name: 'Position test', content }),
        readConfigFile: async () => '', getRuntimeMappingState: async () => ({ mappingEnabled: true, autoloadEnabled: true, controllerNavEnabled: true, firmwareSoundPromptDone: true }),
        saveLibraryProfile: async (name, next) => { content = next; localStorage.setItem('__positionProfile', next); window.__positionSaved = next; return { name } },
      }
    })
    await page.goto(process.env.JSM_TEST_URL || 'http://127.0.0.1:1421')
    await page.locator('[data-home-continue]').click()
    await page.getByRole('button', { name: 'Virtual menus', exact: true }).click()
    const row = (label, scope = page) => scope.locator('button.summary-row').filter({ has: page.locator('.summary-row__label').getByText(label, { exact: true }) })
    await page.getByRole('button', { name: 'Create virtual menu', exact: true }).click()
    const rename = async name => { await page.getByPlaceholder('Name this menu').fill(name); await page.getByPlaceholder('Name this menu').press('Enter') }
    await rename('Weapons')
    assert.equal(await row('Menu controls').count(), 1)
    assert.equal(await row('Menu controls 1').count(), 0)
    assert.equal(await page.locator('.virtual-menus__preview-column .virtual-menus__position').count(), 1)
    const position = page.getByRole('region', { name: 'Overlay screen preview', exact: true })
    assert.equal(await row('Horizontal position', position).count(), 1)
    await row('Advanced configuration').click()
    const advanced = page.getByRole('dialog')
    assert.equal(await row('Horizontal position', advanced).count(), 0)
    assert.equal(await row('Vertical position', advanced).count(), 0)
    await advanced.getByRole('combobox', { name: 'Show overlay', exact: true }).click()
    await page.getByRole('option', { name: 'Never', exact: true }).click()
    await advanced.getByRole('button', { name: 'Close', exact: true }).click()
    await row('Add navigation controls').click()
    assert.match(await page.getByRole('dialog').getAttribute('aria-labelledby'), /.+/)
    await page.getByRole('dialog', { name: 'Weapons · Menu controls 2', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Delete menu controls 2', exact: true }).click()
    assert.equal(await row('Menu controls').count(), 1, 'suffix disappears when one setup remains')
    await page.getByRole('button', { name: 'Create virtual menu', exact: true }).click()
    await rename('Tools')
    await page.getByRole('combobox', { name: 'Menu layout', exact: true }).click()
    await page.getByRole('option', { name: 'Hotbar', exact: true }).click()
    await page.getByRole('button', { name: 'Position all menus', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Position virtual menus', exact: true })
    assert.equal(await dialog.locator('.virtual-menus__screen-menu').count(), 2)
    assert.equal(await dialog.getByText('Overlay hidden', { exact: true }).count(), 1, 'hidden overlays remain available for placement')
    const hotbar = await dialog.locator('[data-menu-id="menu2"]').boundingBox()
    assert.ok(Math.abs(hotbar.width / hotbar.height - 5) < .05, 'other menu shapes retain their screen proportions')
    // Let the sheet entrance animation settle before using absolute mouse coordinates.
    await page.waitForTimeout(300)
    const screen = dialog.getByRole('slider', { name: 'Overlay position', exact: true })
    await screen.press('ArrowRight')
    await screen.press('Shift+ArrowDown')
    assert.match(await screen.getAttribute('aria-valuetext'), /51% across, 55% down/)
    const bounds = await screen.boundingBox()
    await page.mouse.move(bounds.x + bounds.width * .7, bounds.y + bounds.height * .3)
    await page.mouse.down()
    await page.mouse.move(bounds.x + bounds.width * .8, bounds.y + bounds.height * .4, { steps: 4 })
    await page.mouse.up()
    assert.match(await screen.getAttribute('aria-valuetext'), /80% across, 40% down/)
    await dialog.getByRole('button', { name: 'Use this position', exact: true }).click()
    assert.match(await screen.getAttribute('aria-valuetext'), /50% across, 50% down/)
    assert.match(await dialog.getByRole('status').innerText(), /Overlapping footprints: Weapons/)
    await dialog.getByRole('button', { name: /1 Weapons/ }).click()
    await screen.press('ArrowLeft')
    assert.equal(await dialog.locator('[data-menu-id="menu1"]').getAttribute('data-current'), 'true')
    fs.mkdirSync(path.resolve(__dirname, '../tmp/parity-verification'), { recursive: true })
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/menu-position-workspace-wide.png') })
    await page.setViewportSize({ width: 680, height: 740 })
    assert.equal(await dialog.evaluate(node => node.scrollWidth > node.clientWidth), false)
    await row('Vertical position', dialog).scrollIntoViewIfNeeded()
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/menu-position-workspace-narrow.png') })
    await dialog.getByRole('button', { name: 'Close', exact: true }).click()
    await page.setViewportSize({ width: 1600, height: 1000 })
    await page.locator('.virtual-menus__library').scrollIntoViewIfNeeded()
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/menu-position-main-page.png') })
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => !!window.__positionSaved)
    await page.reload()
    await page.locator('[data-home-continue]').click()
    await page.getByRole('button', { name: 'Virtual menus', exact: true }).click()
    await page.getByRole('button', { name: 'Position all menus', exact: true }).click()
    assert.match(await screen.getAttribute('aria-valuetext'), /49% across, 50% down/)
    await dialog.getByRole('button', { name: /2 Tools/ }).click()
    assert.match(await screen.getAttribute('aria-valuetext'), /50% across, 50% down/)
    assert.deepEqual(errors, [])
    console.log('PASS: placement grouping, conditional control names, all-menu dialog, keyboard/drag, matching, overlaps, narrow layout and persisted independent positions')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exit(1) })
