// Isolated renderer with simulated native menu telemetry. No physical output.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const expectControllerInputRing = require('./controller_input_focus_helper.cjs')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/luker/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
    page.setDefaultTimeout(12000)
    const errors = []; page.on('pageerror', error => errors.push(error.message))
    await page.addLocatorHandler(page.getByRole('dialog', { name: 'Controller power-on sound', exact: true }), async () => {
      await page.getByRole('button', { name: 'Keep them', exact: true }).click()
    })
    await page.addInitScript(() => {
      document.hasFocus = () => true
      for (const [key, value] of Object.entries({ width: 2560, availWidth: 2560, height: 1440, availHeight: 1440 })) Object.defineProperty(window.screen, key, { value, configurable: true })
      let content = localStorage.getItem('__menuTestProfile') || 'RESET_MAPPINGS\nLEFT_TOUCHPAD_MODE = MOUSE\nRIGHT_TOUCHPAD_MODE = MOUSE\nUNKNOWN_MENU_FUTURE = untouched\n'
      window.electronAPI = {
        getActiveProfile: async () => ({ name: 'Menu test', path: 'profiles-library/Menu test.txt', content }),
        listLibraryProfiles: async () => ['Menu test'], loadLibraryProfile: async () => ({ name: 'Menu test', content }),
        readConfigFile: async () => '', getRuntimeMappingState: async () => ({ mappingEnabled: true, autoloadEnabled: true, controllerNavEnabled: true, firmwareSoundPromptDone: true }),
        saveLibraryProfile: async (name, next) => { content = next; localStorage.setItem('__menuTestProfile', next); window.__menuSaved = next; return { name } },
        applyProfile: async path => ({ path, mappingEnabled: true }),
      }
      window.__menuButtons = 0
      window.__menuStick = { x: 0, y: 0 }
      window.__menuCursor = undefined
      window.__menuSelected = 2
      window.telemetry = { onSample: callback => {
        const emit = () => callback({ activeProfile: 'AppNavigation.txt', devices: [{ handle: 1, type: 24, status: { buttons: window.__menuButtons, leftStick: { x: 0, y: 0 }, rightStick: window.__menuStick, triggers: { left: 0, right: 0 }, gyro: { x: 0, y: 0, z: 0 }, virtualMenus: [{ id: 'menu1', source: 1, open: true, selected: window.__menuSelected, cursor: window.__menuCursor }] } }] })
        emit(); const timer = setInterval(emit, 100); return () => clearInterval(timer)
      } }
    })
    await page.goto(process.env.JSM_TEST_URL || 'http://127.0.0.1:1421')
    await page.locator('[data-home-continue]').click()

    await page.getByRole('button', { name: 'Virtual menus', exact: true }).click()
    const row = (label, scope = page) => scope.locator('button.summary-row').filter({ has: page.locator('.summary-row__label').getByText(label, { exact: true }) })
    const choose = async (label, value) => { await page.getByRole('combobox', { name: label, exact: true }).click(); await page.getByRole('option', { name: value, exact: true }).click() }
    assert.equal(await page.getByText('No menus yet.', { exact: true }).count(), 1)
    assert.equal(await page.locator('.virtual-menus__editor').innerText(), '', 'empty library does not repeat page instructions')
    await page.getByRole('button', { name: 'Create virtual menu', exact: true }).click()
    await page.getByPlaceholder('Name this menu', { exact: true }).fill('Equipment # wheel')
    await page.getByPlaceholder('Name this menu', { exact: true }).press('Enter')
    const editor = page.locator('[data-virtual-menus-page]')
    await editor.getByRole('heading', { name: 'Equipment # wheel', exact: true }).waitFor()
    assert.equal(await page.getByRole('dialog').count(), 0, 'the menu editor is a full page')
    const positionBox = await page.locator('.virtual-menus__screen').boundingBox()
    const editorBox = await page.locator('.virtual-menus__editor').boundingBox()
    assert.ok(positionBox.width < editorBox.width, 'screen preview belongs to the preview column')
    const controlsBox = await row('Menu controls').boundingBox()
    const addBox = await row('Add navigation controls').boundingBox()
    const advancedBox = await row('Advanced configuration').boundingBox()
    assert.ok(addBox.y - (controlsBox.y + controlsBox.height) >= 11, 'space follows compact menu controls')
    assert.ok(advancedBox.width > 0, 'advanced appearance remains available')
    const menuScale = await page.locator('.virtual-menus__screen-menu').evaluate(node => parseFloat(node.style.width))
    const screenWidth = await page.evaluate(() => screen.availWidth || screen.width)
    assert.ok(Math.abs(menuScale - 360 / screenWidth * 100) < .1, 'full-width preview retains accurate saved menu scale')
    assert.equal(await page.getByRole('combobox', { name: 'Navigation input', exact: true }).count(), 0, 'control options stay out of the main page')
    await row('Menu controls').click()
    const controlsPanel = page.getByRole('dialog', { name: 'Equipment # wheel · Menu controls', exact: true })
    await controlsPanel.waitFor()
    assert.equal(await controlsPanel.getByRole('combobox', { name: 'Navigation input', exact: true }).count(), 1)
    assert.equal(await controlsPanel.getByRole('button', { name: 'Delete menu controls', exact: true }).isVisible(), true)
    await choose('Navigation input', 'Right stick')
    await choose('Navigation mode', 'Joystick cursor')
    await page.evaluate(() => { window.__menuCursor = { x: .75, y: .25 }; window.__menuSelected = 2 })
    const cursor = editor.locator('[class*="_dot_"]').first()
    await page.waitForFunction(() => document.querySelector('[data-virtual-menus-page] [class*="_dot_"]')?.style.transform.includes('75cqw, 25cqh'))
    assert.equal(await cursor.isVisible(), true)
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/named-menu-joystick-cursor.png') })
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => !!window.__menuSaved)
    assert.match(Buffer.from((await page.evaluate(() => window.__menuSaved)).match(/VIRTUAL_MENUS = HEX:([a-f0-9]+)/)[1], 'hex').toString('utf8'), /SOURCE menu1 RSTICK COMMAND NONE ACTIVATION_RELEASE NONE NONE JOYSTICK_CURSOR/)
    await page.reload()
    await page.locator('[data-home-continue]').click()
    await page.getByRole('button', { name: 'Virtual menus', exact: true }).click()
    await row('Menu controls').click()
    assert.match(await page.getByRole('combobox', { name: 'Navigation mode', exact: true }).innerText(), /Joystick cursor/)
    await page.evaluate(() => { window.__menuCursor = { x: .5, y: .5 }; window.__menuSelected = -1 })
    await page.waitForFunction(() => document.querySelector('[data-virtual-menus-page] [class*="_dot_"]')?.style.transform.includes('50cqw, 50cqh'))
    assert.equal(await editor.locator('[data-selected="true"]').count(), 0, 'neutral clears the highlight and keeps the cursor at centre')
    await choose('Navigation mode', 'Joystick')
    await page.evaluate(() => { window.__menuCursor = undefined; window.__menuSelected = 2 })
    await cursor.waitFor({ state: 'detached' })
    await choose('Navigation input', 'Right trackpad')
    assert.equal(await page.getByRole('combobox', { name: 'Navigation mode', exact: true }).count(), 0)
    await choose('Menu activation', 'While an input is held')
    assert.equal(await page.getByRole('combobox', { name: 'Activation input', exact: true }).locator('svg[data-glyph]').count(), 1, 'activation inputs use the controller glyph')
    const explanation = page.locator('.virtual-menus__field').filter({ has: page.getByRole('combobox', { name: 'Activation matches while', exact: true }) }).locator('p')
    assert.match(await explanation.innerText(), /capacitive sensor detects contact/)
    assert.equal(await explanation.evaluate(node => getComputedStyle(node).whiteSpace), 'normal')
    await page.getByRole('combobox', { name: 'Activation matches while', exact: true }).click()
    await page.getByRole('option', { name: 'Released', exact: true }).hover()
    await page.getByText('The activation button is not pressed, or the chosen capacitive sensor detects no touch.', { exact: true }).waitFor()
    await page.getByRole('option', { name: 'Released', exact: true }).click()
    await choose('Menu activation', 'Binding commands')
    await choose('Select action', 'Click or confirm')
    await choose('Confirm input', 'RB')
    await choose('Cancel input', 'B')
    await page.setViewportSize({ width: 680, height: 740 })
    assert.equal(await controlsPanel.evaluate(node => node.scrollWidth > node.clientWidth), false, 'controls fit a narrow detail panel')
    await controlsPanel.getByRole('button', { name: 'Delete menu controls', exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/named-menu-controls-panel.png') })
    await page.setViewportSize({ width: 1440, height: 1000 })
    await controlsPanel.getByRole('button', { name: 'Close', exact: true }).click()
    assert.equal(await row('Actions', editor).count(), 0, 'preview replaces the redundant actions accordion')
    await editor.getByText('Choose Edit actions to select an action from the menu preview. Point the stick around the wheel; D-pad right/down steps clockwise and left/up steps back. Select edits the action; Back leaves the preview. You can also click any action.', { exact: true }).waitFor()
    const previewAction = editor.getByRole('button', { name: 'menu1:0: Weapon 1', exact: true })
    await page.mouse.move(0, 0)
    const idleColor = await previewAction.evaluate(node => getComputedStyle(node).backgroundColor)
    // A radial region's bounding box is the entire wheel; hover inside its top slice.
    await previewAction.hover({ position: { x: 180, y: 65 } })
    await page.waitForTimeout(150)
    assert.notEqual(await previewAction.evaluate(node => getComputedStyle(node).backgroundColor), idleColor, 'hover lights the editable segment')
    assert.equal(await previewAction.evaluate(node => getComputedStyle(node).cursor), 'pointer')
    await editor.getByRole('button', { name: 'menu1:0: Weapon 1', exact: true }).press('Enter')
    const item = page.getByRole('dialog', { name: 'Equipment # wheel · Weapon 1', exact: true })
    await item.waitFor()
    await expectControllerInputRing(page, item.getByRole('textbox', { name: 'Action name', exact: true }), 'Virtual menu action name')
    await item.getByRole('textbox', { name: 'Action name', exact: true }).fill('Primary weapon')
    await item.getByRole('textbox', { name: 'Action name', exact: true }).press('Enter')
    const renamedItem = page.getByRole('dialog', { name: 'Equipment # wheel · Primary weapon', exact: true })
    await renamedItem.waitFor()
    await renamedItem.getByRole('button', { name: 'Change icon', exact: true }).click()
    const icons = page.getByRole('dialog').last()
    await expectControllerInputRing(page, icons.getByRole('searchbox', { name: 'Search icons', exact: true }), 'Icon search')
    fs.mkdirSync(path.resolve(__dirname, '../tmp/parity-verification'), { recursive: true })
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/icon-search-single-ring.png') })
    await icons.getByRole('button', { name: 'arrow-up', exact: true }).click()
    assert.equal(await renamedItem.getByRole('button', { name: 'Change icon', exact: true }).getAttribute('title'), 'lucide:arrow-up')
    await page.setViewportSize({ width: 680, height: 740 })
    assert.equal(await renamedItem.evaluate(node => node.scrollWidth > node.clientWidth), false, 'action identity controls fit a narrow panel')
    assert.ok((await renamedItem.getByRole('textbox', { name: 'Action name', exact: true }).boundingBox()).height <= 48, 'action name remains a compact input')
    fs.mkdirSync(path.resolve(__dirname, '../tmp/parity-verification'), { recursive: true })
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/named-menu-action-panel.png') })
    await page.setViewportSize({ width: 1440, height: 1000 })
    await renamedItem.getByRole('textbox', { name: 'Action name', exact: true }).fill('Weapon 1')
    await renamedItem.getByRole('textbox', { name: 'Action name', exact: true }).press('Enter')
    await row('Add command', item).click()
    const picker = page.getByRole('dialog', { name: 'Choose an action', exact: true })
    await expectControllerInputRing(page, picker.getByRole('searchbox', { name: 'Search all actions', exact: true }), 'Action picker search')
    await picker.locator('.action-tab').filter({ hasText: /^Keyboard$/ }).click()
    await picker.locator('.key-cap[title="2"]').click()
    assert.equal(await item.locator('[data-command-row]').count(), 2)
    await item.getByRole('button', { name: 'Close', exact: true }).click()
    await row('Centre action', editor).click()
    await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    await choose('Menu layout', 'Hotbar')
    await row('Menu controls').click()
    await choose('Navigation input', 'Face buttons')
    await controlsPanel.getByRole('button', { name: 'Close', exact: true }).click()
    const screen = page.getByRole('slider', { name: 'Overlay position', exact: true })
    await screen.scrollIntoViewIfNeeded()
    const screenBox = await screen.boundingBox()
    await screen.click({ position: { x: screenBox.width * .3, y: screenBox.height * .7 } })
    await screen.press('ArrowRight')
    assert.match(await screen.getAttribute('aria-valuetext'), /31% across, 7[01]% down/)
    await row('Advanced configuration', editor).click()
    const advanced = page.getByRole('dialog', { name: 'Equipment # wheel · Advanced configuration', exact: true })
    // Navigate without locator auto-scrolling: the complete bottom row must
    // enter the nested settings viewport, leaving the preview fixed.
    for (const viewport of [{ width: 1440, height: 650 }, { width: 680, height: 740 }]) {
      await page.setViewportSize(viewport)
      await advanced.getByRole('combobox', { name: 'Show overlay', exact: true }).focus()
      for (let index = 0; index < 6; index++) await page.keyboard.press('ArrowDown')
      await page.waitForTimeout(500)
      const visibility = await row('Icons', advanced).evaluate(node => {
        const frame = node.closest('.virtual-menus__advanced').getBoundingClientRect()
        const box = node.getBoundingClientRect()
        return { focused: document.activeElement === node, top: box.top - frame.top, bottom: frame.bottom - box.bottom }
      })
      assert.ok(visibility.focused && visibility.top >= 7 && visibility.bottom >= 7, `bottom row fully visible at ${viewport.width}px: ${JSON.stringify(visibility)}`)
      await page.screenshot({ path: path.resolve(__dirname, `../tmp/parity-verification/named-menu-bottom-${viewport.width}.png`) })
      const column = advanced.locator('.virtual-menus__advanced')
      await column.evaluate(node => { node.scrollTop = 0 })
      await page.evaluate(() => { window.__menuStick = { x: 0, y: -1 } })
      await page.waitForFunction(() => {
        const node = document.querySelector('.virtual-menu-appearance > .virtual-menus__advanced')
        return node && node.scrollTop >= node.scrollHeight - node.clientHeight - 1
      })
      await page.evaluate(() => { window.__menuStick = { x: 0, y: 0 } })
      assert.equal(await column.evaluate(node => node.closest('.sheet__body').scrollTop), 0, 'only the inner settings column scrolls')
    }
    await page.setViewportSize({ width: 1440, height: 1000 })
    const iconSetting = row('Icons', advanced)
    await iconSetting.click()
    assert.match(await iconSetting.innerText(), /On/,'entering adjustment preserves the current value')
    await page.keyboard.press('ArrowLeft')
    assert.match(await iconSetting.innerText(), /Off/)
    await page.keyboard.press('Escape')
    assert.match(await iconSetting.innerText(), /On/,'B restores a boolean setting without closing the sheet')
    await iconSetting.click(); await page.keyboard.press('ArrowLeft'); await page.keyboard.press('Enter')
    assert.match(await iconSetting.innerText(), /Off/,'A keeps the chosen value')
    await iconSetting.click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    await row('Menu width', advanced).click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    assert.match(await row('Menu width', advanced).innerText(), /370/)
    await row('Action label size', advanced).click(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter')
    await choose('Show overlay', 'While activated and navigating')
    await choose('Show overlay', 'While navigating with an action highlighted')
    await choose('Show overlay', 'Never')
    assert.equal(await advanced.locator('.virtual-menu-appearance__canvas').isVisible(), true, 'Never keeps the editor preview visible')
    const appearance = advanced.getByRole('region', { name: 'Live appearance preview', exact: true })
    await appearance.getByText('370 px wide · 19 px action labels · 18 px output names. Preview scales down to fit when needed.', { exact: true }).waitFor()
    const previewFits = async () => {
      await page.waitForTimeout(150)
      const bounds = await appearance.locator('.virtual-menu-appearance__canvas').evaluate(canvas => {
        const drawing = canvas.firstElementChild.firstElementChild.getBoundingClientRect()
        const frame = canvas.getBoundingClientRect()
        return { left: drawing.left - frame.left, top: drawing.top - frame.top, right: frame.right - drawing.right, bottom: frame.bottom - drawing.bottom }
      })
      assert.ok(Object.values(bounds).every(value => value >= -1), `entire live menu stays visible: ${JSON.stringify(bounds)}`)
    }
    await row('Menu width', advanced).click(); await page.keyboard.type('1600'); await page.keyboard.press('Enter')
    await appearance.getByText(/^1600 px wide/).waitFor()
    await previewFits()
    const beforeScroll = await appearance.boundingBox()
    await row('Icons', advanced).scrollIntoViewIfNeeded()
    const afterScroll = await appearance.boundingBox()
    assert.ok(Math.abs(beforeScroll.y - afterScroll.y) < 1, 'scrolling appearance controls leaves the preview pinned')
    await page.setViewportSize({ width: 680, height: 740 })
    await previewFits()
    assert.equal(await advanced.evaluate(node => node.scrollWidth > node.clientWidth), false, 'appearance editor fits a narrow window')
    await page.setViewportSize({ width: 1440, height: 1000 })
    await row('Menu width', advanced).click(); await page.keyboard.type('370'); await page.keyboard.press('Enter')
    fs.mkdirSync(path.resolve(__dirname, '../tmp/parity-verification'), { recursive: true })
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/named-menu-appearance.png') })
    await advanced.getByRole('button', { name: 'Close', exact: true }).click()
    fs.mkdirSync(path.resolve(__dirname, '../tmp/parity-verification'), { recursive: true })
    await screen.scrollIntoViewIfNeeded()
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/named-menu-position.png') })
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => !!window.__menuSaved)
    let saved = await page.evaluate(() => window.__menuSaved)
    assert.match(saved, /LEFT_TOUCHPAD_MODE = MOUSE/)
    assert.match(saved, /RIGHT_TOUCHPAD_MODE = MOUSE/)
    assert.match(saved, /UNKNOWN_MENU_FUTURE = untouched/)
    const packed = Buffer.from(saved.match(/VIRTUAL_MENUS = HEX:([a-f0-9]+)/)[1], 'hex').toString('utf8')
    assert.match(packed, /DEFINE menu1 HOTBAR 8 8 0.28/)
    assert.match(packed, /SOURCE menu1 ABXY COMMAND/)
    assert.match(packed, /Equipment # wheel/)
    assert.match(packed, /"reveal":"never"/)
    await page.reload()
    await page.locator('[data-home-continue]').click()
    await page.getByRole('button', { name: 'Virtual menus', exact: true }).click()
    assert.match(await page.getByRole('combobox', { name: 'Menu layout', exact: true }).innerText(), /Hotbar/)
    assert.match(await screen.getAttribute('aria-valuetext'), /31% across, 7[01]% down/)
    await row('Delete this menu').click()
    assert.equal(await page.getByRole('alert').count(), 0, 'deleting the last configured menu does not lock the catalog')
    await page.getByRole('button', { name: 'Create virtual menu', exact: true }).click()
    await row('Menu controls').click()
    await page.getByRole('button', { name: 'Delete menu controls', exact: true }).click()
    assert.equal(await page.getByRole('dialog').count(), 0, 'deleting controls closes the panel')
    assert.equal(await row('Menu controls').count(), 0, 'deleted controls leave the main page')
    assert.equal(await page.locator('.virtual-menus__preview').isVisible(), true, 'deleting controls preserves the menu')
    await row('Add navigation controls').click()
    await page.getByRole('dialog', { name: 'Weapon Wheel · Menu controls', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Delete menu controls', exact: true }).click()
    await row('Delete this menu').click()
    assert.equal(await page.getByRole('alert').count(), 0, 'deleting a partially configured menu leaves the editor usable')
    await page.getByRole('button', { name: 'Create virtual menu', exact: true }).click()
    await page.getByRole('button', { name: 'Buttons', exact: true }).click()

    const card = input => page.locator(`details[data-input-command="${input}"]`).first()
    for (const [input, verb] of [['L', 'Hold'], ['R', 'Open']]) {
      await card(input).locator(':scope > summary').click()
      await card(input).getByRole('button', { name: 'Add command', exact: true }).click()
      const actionPicker = page.getByRole('dialog', { name: 'Choose an action', exact: true })
      await actionPicker.locator('.action-tab').filter({ hasText: /^Virtual menus$/ }).click()
      for (const label of ['Open', 'Close', 'Toggle', 'Hold']) assert.equal(await actionPicker.getByRole('button', { name: `${label} Weapon Wheel`, exact: true }).count(), 1)
      await actionPicker.getByRole('button', { name: `${verb} Weapon Wheel`, exact: true }).click()
      assert.match(await card(input).innerText(), new RegExp(`${verb} menu`))
    }
    await page.keyboard.press('Control+s')
    await page.waitForFunction(() => /MENU_HOLD menu1/.test(window.__menuSaved) && /MENU_OPEN menu1/.test(window.__menuSaved))
    saved = await page.evaluate(() => window.__menuSaved)
    assert.match(saved, /^L = "MENU_HOLD menu1"/m)
    assert.match(saved, /^R = "MENU_OPEN menu1"/m)
    await page.reload()
    await page.locator('[data-home-continue]').click()
    await page.getByRole('button', { name: 'Buttons', exact: true }).click()
    await card('L').locator(':scope > summary').click()
    await page.waitForFunction(() => document.querySelector('details[data-input-command="L"]')?.innerText.includes('Hold menu'))
    assert.match(await card('L').innerText(), /Hold menu/)
    await page.getByRole('button', { name: 'Virtual menus', exact: true }).click()
    await row('Advanced configuration').click()
    const wheelAppearance = page.getByRole('dialog', { name: 'Weapon Wheel · Advanced configuration', exact: true })
    await row('Menu width', wheelAppearance).click(); await page.keyboard.type('1600'); await page.keyboard.press('Enter')
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/named-menu-appearance-large.png') })
    const wheelFits = await wheelAppearance.locator('.virtual-menu-appearance__canvas').evaluate(canvas => {
      const menu = canvas.firstElementChild.firstElementChild.getBoundingClientRect(), frame = canvas.getBoundingClientRect()
      return menu.left >= frame.left - 1 && menu.right <= frame.right + 1 && menu.top >= frame.top - 1 && menu.bottom <= frame.bottom + 1
    })
    assert.ok(wheelFits, 'a maximum-size radial menu is fully visible while editing')
    await wheelAppearance.getByRole('button', { name: 'Close', exact: true }).click()
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/named-menu-editor.png') })
    await page.waitForTimeout(250)
    await page.setViewportSize({ width: 850, height: 850 })
    await page.screenshot({ path: path.resolve(__dirname, '../tmp/parity-verification/named-menu-narrow.png') })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, 'full page fits a narrow viewport')

    assert.deepEqual(errors, [])
    console.log('PASS: full virtual menus page, glyphs, described dropdowns, condition help, action editing, face-button hotbar, screen positioning, advanced sheet, save/reload and final-menu deletion/recreation')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exit(1) })
