// The bundled FPS starter (System States 17d, "FPS Template · Gyro aim on
// grip, pads as mouse and menu"). The app ships no template file of its own,
// so this is the text the first-run choice writes into the library. Steam
// Controller names: MISC5 is the right grip, LSL/LSR/RSR/RSL the paddles,
// MISC2/MISC3 the pad clicks (see keymap/schema.ts).
export const FPS_TEMPLATE_NAME = 'FPS Template'

export const FPS_TEMPLATE_TEXT = [
  '# FPS Template: gyro aim while the right grip is held, the right pad as a',
  '# mouse, the left pad as a four-way menu. Import it from a game profile and',
  '# override what the game needs.',
  'RESET_MAPPINGS',
  'AUTOCONNECT = ON',
  '',
  '# Face, bumpers, triggers',
  'S = SPACE',
  'E = C',
  'W = R',
  'N = F',
  'L = G',
  'R = MMOUSE',
  'ZL = RMOUSE',
  'ZR = LMOUSE',
  'ZL_MODE = NO_FULL',
  'ZR_MODE = NO_FULL',
  '',
  '# Paddles',
  'LSL = Q',
  'LSR = SHIFT',
  'RSR = E',
  'RSL = CONTROL',
  '',
  '# Menu buttons',
  '+ = ESC',
  '- = TAB',
  '',
  '# Sticks',
  'LEFT_STICK_MODE = NO_MOUSE',
  'LUP = W',
  'LDOWN = S',
  'LLEFT = A',
  'LRIGHT = D',
  'L3 = LSHIFT',
  'RIGHT_STICK_MODE = AIM',
  'R3 = V',
  '',
  '# Pads: right pad is the mouse, left pad a four-way menu',
  'RIGHT_TOUCHPAD_MODE = MOUSE',
  'MISC2 = LMOUSE',
  'LEFT_TOUCHPAD_MODE = GRID_AND_STICK',
  'LEFT_GRID_SIZE = 2 2',
  'LT1 = 1',
  'LT2 = 2',
  'LT3 = 3',
  'LT4 = 4',
  'MISC3 = M',
  '',
  '# Gyro: aim while the right grip is held',
  'GYRO_ON = MISC5',
  'GYRO_SENS = 2 2',
  'GYRO_SPACE = PLAYER_TURN',
  'REAL_WORLD_CALIBRATION = 45',
  'IN_GAME_SENS = 1',
  'GYRO_SMOOTH_THRESHOLD = 5',
  'GYRO_CUTOFF_SPEED = 0.5',
  'AUTO_CALIBRATE_GYRO = ON',
  '',
].join('\n')
