// Generated by scripts/audit-jsm-inputs.py from the native ButtonID enum.
// Do not use engine names as the primary controller-facing labels.
export const NATIVE_INPUTS = [
  'NONE', 'UP', 'DOWN', 'LEFT', 'RIGHT', 'L', 'ZL', 'MINUS',
  'E', 'S', 'N', 'W', 'R', 'ZR', 'PLUS', 'HOME',
  'LSL', 'LSR', 'RSL', 'RSR', 'L3', 'R3', 'LEAN_LEFT', 'LEAN_RIGHT',
  'MIC', 'LUP', 'LDOWN', 'LLEFT', 'LRIGHT', 'LRING', 'RUP', 'RDOWN',
  'RLEFT', 'RRIGHT', 'RRING', 'MUP', 'MDOWN', 'MLEFT', 'MRIGHT', 'MRING',
  'TOUCH', 'LTOUCH', 'RTOUCH', 'LMINI', 'RMINI', 'MISC1', 'MISC2', 'MISC3',
  'MISC4', 'MISC5', 'MISC6', 'ZLF', 'CAPTURE', 'ZRF', 'TUP', 'TDOWN',
  'TLEFT', 'TRIGHT', 'TRING', 'T1', 'T2', 'T3', 'T4', 'T5',
  'T6', 'T7', 'T8', 'T9', 'T10', 'T11', 'T12', 'T13',
  'T14', 'T15', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21',
  'T22', 'T23', 'T24', 'T25', 'LT1', 'LT2', 'LT3', 'LT4',
  'LT5', 'LT6', 'LT7', 'LT8', 'LT9', 'LT10', 'LT11', 'LT12',
  'LT13', 'LT14', 'LT15', 'LT16', 'LT17', 'LT18', 'LT19', 'LT20',
  'LT21', 'LT22', 'LT23', 'LT24', 'LT25', 'RT1', 'RT2', 'RT3',
  'RT4', 'RT5', 'RT6', 'RT7', 'RT8', 'RT9', 'RT10', 'RT11',
  'RT12', 'RT13', 'RT14', 'RT15', 'RT16', 'RT17', 'RT18', 'RT19',
  'RT20', 'RT21', 'RT22', 'RT23', 'RT24', 'RT25', 'LM1', 'LM2',
  'LM3', 'LM4', 'LM5', 'LM6', 'LM7', 'LM8', 'LM9', 'LM10',
  'LM11', 'LM12', 'LM13', 'LM14', 'LM15', 'LM16', 'LM17', 'LM18',
  'LM19', 'LM20', 'LM21', 'LM22', 'LM23', 'LM24', 'LM25', 'RM1',
  'RM2', 'RM3', 'RM4', 'RM5', 'RM6', 'RM7', 'RM8', 'RM9',
  'RM10', 'RM11', 'RM12', 'RM13', 'RM14', 'RM15', 'RM16', 'RM17',
  'RM18', 'RM19', 'RM20', 'RM21', 'RM22', 'RM23', 'RM24', 'RM25',
] as const

export const RELEASE_CONDITION_INPUTS = [
  'UP', 'DOWN', 'LEFT', 'RIGHT', 'L', 'ZL', 'MINUS', 'E',
  'S', 'N', 'W', 'R', 'ZR', 'PLUS', 'HOME', 'LSL',
  'LSR', 'RSL', 'RSR', 'L3', 'R3', 'LEAN_LEFT', 'LEAN_RIGHT', 'MIC',
  'LUP', 'LDOWN', 'LLEFT', 'LRIGHT', 'LRING', 'RUP', 'RDOWN', 'RLEFT',
  'RRIGHT', 'RRING', 'MUP', 'MDOWN', 'MLEFT', 'MRIGHT', 'MRING', 'TOUCH',
  'LTOUCH', 'RTOUCH', 'LMINI', 'RMINI', 'MISC1', 'MISC2', 'MISC3', 'MISC4',
  'MISC5', 'MISC6', 'ZLF', 'CAPTURE', 'ZRF', 'TUP', 'TDOWN', 'TLEFT',
  'TRIGHT', 'TRING',
] as const

const heldInputs = new Set<string>([...NATIVE_INPUTS, '+', '-'])
const releasedInputs = new Set<string>([...RELEASE_CONDITION_INPUTS, '+', '-'])

/** Native released conditions are supported for physical/derived inputs,
 * while touch-grid/stick-menu cells only exist while their source is active. */
export function isNativeInput(input: string): boolean {
  return input.startsWith('!') ? releasedInputs.has(input.slice(1)) : heldInputs.has(input)
}
