// Generated by scripts/build-design-icons.mjs from design/handoff. Do not edit.

/** Steam Controller glyphs by design key: label, JSM id and inner SVG markup
 *  (24 grid). Knocked-out marks use var(--glyph-ink). */
export const STEAM_GLYPHS: Record<string, { label: string; id: string; svg: string }> = {
  "S": {
    "label": "A",
    "id": "S",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">A</text>"
  },
  "E": {
    "label": "B",
    "id": "E",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">B</text>"
  },
  "W": {
    "label": "X",
    "id": "W",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">X</text>"
  },
  "N": {
    "label": "Y",
    "id": "N",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">Y</text>"
  },
  "L": {
    "label": "LB",
    "id": "L",
    "svg": "<path d=\"M2.5 17V11.5A5.5 5.5 0 0 1 8 6h8a5.5 5.5 0 0 1 5.5 5.5V17a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1z\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">LB</text>"
  },
  "R": {
    "label": "RB",
    "id": "R",
    "svg": "<path d=\"M2.5 17V11.5A5.5 5.5 0 0 1 8 6h8a5.5 5.5 0 0 1 5.5 5.5V17a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1z\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">RB</text>"
  },
  "ZL": {
    "label": "LT",
    "id": "ZL",
    "svg": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">LT</text>"
  },
  "ZR": {
    "label": "RT",
    "id": "ZR",
    "svg": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">RT</text>"
  },
  "ZLF": {
    "label": "LT full",
    "id": "ZLF",
    "svg": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">LT</text><path d=\"M8 21.5h8\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.6\"/>"
  },
  "ZRF": {
    "label": "RT full",
    "id": "ZRF",
    "svg": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">RT</text><path d=\"M8 21.5h8\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.6\"/>"
  },
  "LS": {
    "label": "Left stick",
    "id": "LEFT_STICK",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"12\" cy=\"12\" r=\"6\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"6.5\" fill=\"var(--glyph-ink)\">L</text>"
  },
  "RS": {
    "label": "Right stick",
    "id": "RIGHT_STICK",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"12\" cy=\"12\" r=\"6\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"6.5\" fill=\"var(--glyph-ink)\">R</text>"
  },
  "L3": {
    "label": "Left stick click",
    "id": "L3",
    "svg": "<circle cx=\"12\" cy=\"10.5\" r=\"8\" fill=\"currentColor\"/><text x=\"12\" y=\"11\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"6.5\" fill=\"var(--glyph-ink)\">L3</text><path d=\"M8.5 20.5h7\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>"
  },
  "R3": {
    "label": "Right stick click",
    "id": "R3",
    "svg": "<circle cx=\"12\" cy=\"10.5\" r=\"8\" fill=\"currentColor\"/><text x=\"12\" y=\"11\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"6.5\" fill=\"var(--glyph-ink)\">R3</text><path d=\"M8.5 20.5h7\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>"
  },
  "LST": {
    "label": "Left stick touch",
    "id": "LEFT_STICK_TOUCH",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"12\" cy=\"12\" r=\"6\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"12\" cy=\"12\" r=\"2\" fill=\"currentColor\"/>"
  },
  "LRING": {
    "label": "Left stick ring",
    "id": "LRING",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-dasharray=\"3 2.5\"/><circle cx=\"12\" cy=\"12\" r=\"5\" fill=\"currentColor\"/>"
  },
  "LUP": {
    "label": "Left stick up",
    "id": "LUP",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M12 4 15 8h-6z\" fill=\"currentColor\" transform=\"rotate(0 12 12)\"/><circle cx=\"12\" cy=\"12.5\" r=\"2.25\" fill=\"currentColor\"/>"
  },
  "LRIGHT": {
    "label": "Left stick right",
    "id": "LRIGHT",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M12 4 15 8h-6z\" fill=\"currentColor\" transform=\"rotate(90 12 12)\"/><circle cx=\"12\" cy=\"12.5\" r=\"2.25\" fill=\"currentColor\"/>"
  },
  "LDOWN": {
    "label": "Left stick down",
    "id": "LDOWN",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M12 4 15 8h-6z\" fill=\"currentColor\" transform=\"rotate(180 12 12)\"/><circle cx=\"12\" cy=\"12.5\" r=\"2.25\" fill=\"currentColor\"/>"
  },
  "LLEFT": {
    "label": "Left stick left",
    "id": "LLEFT",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M12 4 15 8h-6z\" fill=\"currentColor\" transform=\"rotate(270 12 12)\"/><circle cx=\"12\" cy=\"12.5\" r=\"2.25\" fill=\"currentColor\"/>"
  },
  "DPAD": {
    "label": "D-pad",
    "id": "DPAD",
    "svg": "<path d=\"M9 2.5h6v6.5h6.5v6H15v6.5H9V15H2.5V9H9z\" fill=\"currentColor\"/>"
  },
  "UP": {
    "label": "D-pad up",
    "id": "UP",
    "svg": "<path d=\"M9 2.5h6v6.5h6.5v6H15v6.5H9V15H2.5V9H9z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linejoin=\"round\"/><path d=\"M9 2.5h6V9H9z\" fill=\"currentColor\"/>"
  },
  "RIGHT": {
    "label": "D-pad right",
    "id": "RIGHT",
    "svg": "<path d=\"M9 2.5h6v6.5h6.5v6H15v6.5H9V15H2.5V9H9z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linejoin=\"round\"/><path d=\"M15 9h6.5v6H15z\" fill=\"currentColor\"/>"
  },
  "DOWN": {
    "label": "D-pad down",
    "id": "DOWN",
    "svg": "<path d=\"M9 2.5h6v6.5h6.5v6H15v6.5H9V15H2.5V9H9z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linejoin=\"round\"/><path d=\"M9 15h6v6.5H9z\" fill=\"currentColor\"/>"
  },
  "LEFT": {
    "label": "D-pad left",
    "id": "LEFT",
    "svg": "<path d=\"M9 2.5h6v6.5h6.5v6H15v6.5H9V15H2.5V9H9z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linejoin=\"round\"/><path d=\"M2.5 9H9v6H2.5z\" fill=\"currentColor\"/>"
  },
  "MINUS": {
    "label": "View",
    "id": "MINUS",
    "svg": "<rect x=\"1\" y=\"5\" width=\"22\" height=\"14\" rx=\"7\" fill=\"currentColor\"/><path d=\"M6 13V8h7\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"2\"/><rect x=\"9\" y=\"10\" width=\"9\" height=\"6\" rx=\"1\" fill=\"var(--glyph-ink)\"/>"
  },
  "PLUS": {
    "label": "Menu",
    "id": "PLUS",
    "svg": "<rect x=\"1\" y=\"5\" width=\"22\" height=\"14\" rx=\"7\" fill=\"currentColor\"/><path d=\"M7 9h10M7 12h10M7 15h10\" stroke=\"var(--glyph-ink)\" stroke-width=\"2\"/>"
  },
  "HOME": {
    "label": "Steam",
    "id": "HOME",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><circle cx=\"14.8\" cy=\"9.4\" r=\"3.4\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.5\"/><circle cx=\"14.8\" cy=\"9.4\" r=\"1.7\" fill=\"var(--glyph-ink)\"/><circle cx=\"8.9\" cy=\"15.4\" r=\"2\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.4\"/><path d=\"m10.3 14 2.4-2.5M7.1 14.7 2.4 12.8\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>"
  },
  "MISC1": {
    "label": "Quick Access",
    "id": "MISC1",
    "svg": "<rect x=\"2.5\" y=\"6.5\" width=\"19\" height=\"11\" rx=\"5.5\" fill=\"currentColor\"/><circle cx=\"8\" cy=\"12\" r=\"1.4\" fill=\"var(--glyph-ink)\"/><circle cx=\"12\" cy=\"12\" r=\"1.4\" fill=\"var(--glyph-ink)\"/><circle cx=\"16\" cy=\"12\" r=\"1.4\" fill=\"var(--glyph-ink)\"/>"
  },
  "LSL": {
    "label": "L4",
    "id": "LSL",
    "svg": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"5.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"8.5\" fill=\"currentColor\">L4</text>"
  },
  "LSR": {
    "label": "L5",
    "id": "LSR",
    "svg": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"5.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"8.5\" fill=\"currentColor\">L5</text>"
  },
  "RSR": {
    "label": "R4",
    "id": "RSR",
    "svg": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"5.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"8.5\" fill=\"currentColor\">R4</text>"
  },
  "RSL": {
    "label": "R5",
    "id": "RSL",
    "svg": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"5.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"8.5\" fill=\"currentColor\">R5</text>"
  },
  "MISC6": {
    "label": "Left grip",
    "id": "MISC6",
    "svg": "<path d=\"M6 2.5h9.2a2.5 2.5 0 0 1 2.46 2.95L15.5 19.2a2.5 2.5 0 0 1-2.46 2.3H6A2.5 2.5 0 0 1 3.5 19V5A2.5 2.5 0 0 1 6 2.5z\" fill=\"currentColor\"/><text x=\"10\" y=\"8.2\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">LG</text><path d=\"M5.5 14.5h9.5M5.5 17h9M5.5 19.5h8.6\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.2\" stroke-linecap=\"round\"/>"
  },
  "MISC5": {
    "label": "Right grip",
    "id": "MISC5",
    "svg": "<path d=\"M18 2.5H8.8a2.5 2.5 0 0 0-2.46 2.95L8.5 19.2a2.5 2.5 0 0 0 2.46 2.3H18a2.5 2.5 0 0 0 2.5-2.5V5A2.5 2.5 0 0 0 18 2.5z\" fill=\"currentColor\"/><text x=\"14\" y=\"8.2\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">RG</text><path d=\"M9 14.5h9.5M9.3 17h9.2M9.6 19.5h8.9\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.2\" stroke-linecap=\"round\"/>"
  },
  "MISC3": {
    "label": "Left pad click",
    "id": "MISC3",
    "svg": "<rect x=\"2.5\" y=\"2.5\" width=\"19\" height=\"19\" rx=\"5.5\" fill=\"currentColor\"/><text x=\"12\" y=\"11\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"8.5\" fill=\"var(--glyph-ink)\">L</text><path d=\"M9.5 16.5h5\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>"
  },
  "MISC2": {
    "label": "Right pad click",
    "id": "MISC2",
    "svg": "<rect x=\"2.5\" y=\"2.5\" width=\"19\" height=\"19\" rx=\"5.5\" fill=\"currentColor\"/><text x=\"12\" y=\"11\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"8.5\" fill=\"var(--glyph-ink)\">R</text><path d=\"M9.5 16.5h5\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>"
  },
  "LTOUCH": {
    "label": "Pad touch",
    "id": "LEFT_PAD_TOUCH",
    "svg": "<rect x=\"2.5\" y=\"2.5\" width=\"19\" height=\"19\" rx=\"5.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"14\" cy=\"10\" r=\"3\" fill=\"currentColor\"/><circle cx=\"14\" cy=\"10\" r=\"5.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.2\" opacity=\".5\"/>"
  },
  "LT1": {
    "label": "Left pad region 1",
    "id": "LT1",
    "svg": "<rect x=\"2.5\" y=\"2.5\" width=\"19\" height=\"19\" rx=\"5.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M12 2.5v19M2.5 12h19\" stroke=\"currentColor\" stroke-width=\"1.2\" opacity=\".5\"/><path d=\"M8 2.5h4V12H2.5V8A5.5 5.5 0 0 1 8 2.5z\" fill=\"currentColor\"/><text x=\"7.2\" y=\"7.6\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"6.5\" fill=\"var(--glyph-ink)\">1</text>"
  },
  "RM1": {
    "label": "Right wheel segment 1",
    "id": "RM1",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M12 12 12 2.5A9.5 9.5 0 0 1 18.7 5.3z\" fill=\"currentColor\"/><text x=\"12\" y=\"15.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7\" fill=\"currentColor\">1</text>"
  },
  "GYRO": {
    "label": "Gyro",
    "id": "GYRO",
    "svg": "<circle cx=\"12\" cy=\"12\" r=\"11\" fill=\"currentColor\"/><ellipse cx=\"12\" cy=\"11\" rx=\"2.9\" ry=\"5.6\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.5\"/><ellipse cx=\"12\" cy=\"11\" rx=\"6\" ry=\"2.2\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.5\"/><path d=\"M12 16.6v2.4M9.4 19h5.2\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
  }
}

/** Small cuts for 20px and below, by design key. Missing keys are derived
 *  from a sibling in InputGlyph (N from S, R from L, and so on). */
export const STEAM_SMALL_GLYPHS: Record<string, string> = {
  "DPAD": "<path d=\"M8.5 2h7v6.5H22v7h-6.5V22h-7v-6.5H2v-7h6.5z\" fill=\"currentColor\"></path>",
  "E": "<circle cx=\"12\" cy=\"12\" r=\"11\" fill=\"currentColor\"></circle><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"14\" fill=\"var(--glyph-ink)\">B</text>",
  "GYRO": "<circle cx=\"12\" cy=\"12\" r=\"11\" fill=\"currentColor\"></circle><ellipse cx=\"12\" cy=\"11\" rx=\"3.2\" ry=\"6\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"2.2\"></ellipse><ellipse cx=\"12\" cy=\"11\" rx=\"6.5\" ry=\"2.4\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"2.2\"></ellipse>",
  "HOME": "<circle cx=\"12\" cy=\"12\" r=\"11\" fill=\"currentColor\"/><circle cx=\"15\" cy=\"9.2\" r=\"3.6\" fill=\"var(--glyph-ink)\"/><circle cx=\"8.6\" cy=\"15.6\" r=\"2.4\" fill=\"var(--glyph-ink)\"/><path d=\"m10.2 14 2.7-2.7M6.8 14.8 1.8 12.8\" stroke=\"var(--glyph-ink)\" stroke-width=\"2\" stroke-linecap=\"round\"/>",
  "L": "<path d=\"M1.5 18V11.5A5.5 5.5 0 0 1 7 6h10a5.5 5.5 0 0 1 5.5 5.5V18a1 1 0 0 1-1 1h-19a1 1 0 0 1-1-1z\" fill=\"currentColor\"></path><text x=\"12\" y=\"13\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"12\" fill=\"var(--glyph-ink)\">L</text>",
  "LSL": "<rect x=\"2.5\" y=\"2.5\" width=\"19\" height=\"19\" rx=\"5.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"></rect><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"13\" fill=\"currentColor\">4</text>",
  "LT1": "<rect x=\"2.5\" y=\"2.5\" width=\"19\" height=\"19\" rx=\"5.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"></rect><path d=\"M8 2.5h4V12H2.5V8A5.5 5.5 0 0 1 8 2.5z\" fill=\"currentColor\"></path><text x=\"16.5\" y=\"16.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"10\" fill=\"currentColor\">1</text>",
  "MINUS": "<rect x=\"1.333\" y=\"5.333\" width=\"21.333\" height=\"12\" rx=\"6\" fill=\"currentColor\"/><path d=\"M7.333 14V8.667H14\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.333\"/><rect x=\"9.333\" y=\"10.667\" width=\"8\" height=\"4\" rx=\"0.667\" fill=\"var(--glyph-ink)\"/>",
  "MISC2": "<rect x=\"2\" y=\"2\" width=\"20\" height=\"20\" rx=\"5.5\" fill=\"currentColor\"></rect><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"13\" fill=\"var(--glyph-ink)\">R</text>",
  "MISC5": "<path d=\"M18 2.5H8.8a2.5 2.5 0 0 0-2.46 2.95L8.5 19.2a2.5 2.5 0 0 0 2.46 2.3H18a2.5 2.5 0 0 0 2.5-2.5V5A2.5 2.5 0 0 0 18 2.5z\" fill=\"currentColor\"></path><text x=\"14.2\" y=\"8.8\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"10\" fill=\"var(--glyph-ink)\">R</text><path d=\"M9.3 16h9.2M9.6 19.2h8.9\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.8\" stroke-linecap=\"round\"></path>",
  "MISC6": "<path d=\"M6 2.5h9.2a2.5 2.5 0 0 1 2.46 2.95L15.5 19.2a2.5 2.5 0 0 1-2.46 2.3H6A2.5 2.5 0 0 1 3.5 19V5A2.5 2.5 0 0 1 6 2.5z\" fill=\"currentColor\"></path><text x=\"9.8\" y=\"8.8\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"10\" fill=\"var(--glyph-ink)\">L</text><path d=\"M5.5 16h9.2M5.5 19.2h8.6\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.8\" stroke-linecap=\"round\"></path>",
  "PLUS": "<rect x=\"1.333\" y=\"5.333\" width=\"21.333\" height=\"12\" rx=\"6\" fill=\"currentColor\"/><path d=\"M6.667 8.667h10.667M6.667 11.333h10.667M6.667 14h10.667\" stroke=\"var(--glyph-ink)\" stroke-width=\"1.333\"/>",
  "R3": "<circle cx=\"12\" cy=\"10\" r=\"8.5\" fill=\"currentColor\"></circle><path d=\"M7 21.5h10\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\"></path>",
  "RM1": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"></circle><path d=\"M12 12V2a10 10 0 0 1 7.1 2.9z\" fill=\"currentColor\"></path>",
  "S": "<circle cx=\"12\" cy=\"12\" r=\"11\" fill=\"currentColor\"></circle><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"14\" fill=\"var(--glyph-ink)\">A</text>",
  "ZR": "<path d=\"M4 21.5V9.5a8 8 0 0 1 16 0v12a.5.5 0 0 1-.5.5h-15a.5.5 0 0 1-.5-.5z\" fill=\"currentColor\"></path><text x=\"12\" y=\"14.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"12\" fill=\"var(--glyph-ink)\">R</text>"
}

/** Face buttons and shoulders for the other controller families. */
export const FAMILY_GLYPHS: Record<string, { name: string; items: Record<string, string> }> = {
  "xbox": {
    "name": "Xbox",
    "items": {
      "A": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">A</text>",
      "B": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">B</text>",
      "X": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">X</text>",
      "Y": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">Y</text>",
      "LB": "<path d=\"M2.5 17V11.5A5.5 5.5 0 0 1 8 6h8a5.5 5.5 0 0 1 5.5 5.5V17a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1z\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">LB</text>",
      "RB": "<path d=\"M2.5 17V11.5A5.5 5.5 0 0 1 8 6h8a5.5 5.5 0 0 1 5.5 5.5V17a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1z\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">RB</text>",
      "LT": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">LT</text>",
      "RT": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">RT</text>"
    }
  },
  "ps": {
    "name": "PlayStation",
    "items": {
      "Cross": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><path d=\"M8.5 8.5l7 7M15.5 8.5l-7 7\" stroke=\"var(--glyph-ink)\" stroke-width=\"2\" stroke-linecap=\"round\"/>",
      "Circle": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"4\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"2\"/>",
      "Square": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><rect x=\"8.25\" y=\"8.25\" width=\"7.5\" height=\"7.5\" rx=\"1\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"2\"/>",
      "Triangle": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><path d=\"M12 7.5 16.5 15.5h-9z\" fill=\"none\" stroke=\"var(--glyph-ink)\" stroke-width=\"2\" stroke-linejoin=\"round\"/>",
      "L1": "<path d=\"M2.5 17V11.5A5.5 5.5 0 0 1 8 6h8a5.5 5.5 0 0 1 5.5 5.5V17a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1z\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">L1</text>",
      "R1": "<path d=\"M2.5 17V11.5A5.5 5.5 0 0 1 8 6h8a5.5 5.5 0 0 1 5.5 5.5V17a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1z\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">R1</text>",
      "L2": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">L2</text>",
      "R2": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">R2</text>"
    }
  },
  "nin": {
    "name": "Nintendo",
    "items": {
      "B (south)": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">B</text>",
      "A (east)": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">A</text>",
      "Y (west)": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">Y</text>",
      "X (north)": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"11\" fill=\"var(--glyph-ink)\">X</text>",
      "L": "<path d=\"M2.5 17V11.5A5.5 5.5 0 0 1 8 6h8a5.5 5.5 0 0 1 5.5 5.5V17a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1z\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">L</text>",
      "R": "<path d=\"M2.5 17V11.5A5.5 5.5 0 0 1 8 6h8a5.5 5.5 0 0 1 5.5 5.5V17a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1z\" fill=\"currentColor\"/><text x=\"12\" y=\"12.5\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">R</text>",
      "ZL": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">ZL</text>",
      "ZR": "<path d=\"M5 21V9.5a7 7 0 0 1 14 0V21a.5.5 0 0 1-.5.5h-13A.5.5 0 0 1 5 21z\" fill=\"currentColor\"/><text x=\"12\" y=\"14\" text-anchor=\"middle\" dominant-baseline=\"central\" font-family=\"Geist, 'Segoe UI', system-ui\" font-weight=\"700\" font-size=\"7.5\" fill=\"var(--glyph-ink)\">ZR</text>"
    }
  }
}
