"""Generate the renderer's input validator from the actual native ButtonID enum.

Names are a serialization contract, not a substitute for contextual input labels.
Default mode checks drift; --write regenerates after reviewing backend changes.
"""
import argparse
import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'JSM_GUI/jsm_gui_tauri/src/constants/nativeInputs.ts'
spec = importlib.util.spec_from_file_location('settings_audit', ROOT / 'scripts/audit-jsm-settings.py')
audit = importlib.util.module_from_spec(spec)
spec.loader.exec_module(audit)


def render(header=None):
    values = audit.enums(header or audit.HEADER.read_text(encoding='utf-8-sig'))['ButtonID']
    assert values[:2] == ['INVALID', 'NONE'] and 'SIZE' in values
    names = [value for value in values if value not in {'INVALID', 'SIZE'}]
    released = values[2:values.index('SIZE')]

    def array(name, items):
        rows = [', '.join(repr(value) for value in items[start:start + 8]) for start in range(0, len(items), 8)]
        return f'export const {name} = [\n' + ''.join(f'  {row},\n' for row in rows) + '] as const\n'

    return ('// Generated by scripts/audit-jsm-inputs.py from the native ButtonID enum.\n'
            '// Do not use engine names as the primary controller-facing labels.\n'
            + array('NATIVE_INPUTS', names) + '\n' + array('RELEASE_CONDITION_INPUTS', released)
            + """
const heldInputs = new Set<string>([...NATIVE_INPUTS, '+', '-'])
const releasedInputs = new Set<string>([...RELEASE_CONDITION_INPUTS, '+', '-'])

/** Native released conditions are supported for physical/derived inputs,
 * while touch-grid/stick-menu cells only exist while their source is active. */
export function isNativeInput(input: string): boolean {
  return input.startsWith('!') ? releasedInputs.has(input.slice(1)) : heldInputs.has(input)
}
""")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--output', type=Path, default=TARGET)
    args = parser.parse_args()
    content = render()
    if args.write:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content, encoding='utf-8')
    if not args.output.is_file() or args.output.read_text(encoding='utf-8') != content:
        raise SystemExit('Native input registry drift: review the ButtonID change and regenerate.')
    print('PASS: graphical input validator matches the native ButtonID enum and released-condition boundary')
