import { useConfigHistory } from './useConfigHistory'
import { useMemo, useState } from 'react'
import { getKeymapValue } from '../utils/keymap'
import { keyName } from '../constants/configKeys'
import { useSensitivityConfig } from './useSensitivityConfig'
import { useTouchpadConfig } from './useTouchpadConfig'
import { useGripConfig } from './useGripConfig'
import { useStickConfig } from './useStickConfig'
import { useBindingsConfig } from './useBindingsConfig'
import { useConfigIncludes } from './useConfigIncludes'
import { INCLUDE_ROOT } from '../utils/configIncludes'

export function useKeymapConfig() {
  const history = useConfigHistory()
  const { text: configText, setText: setConfigText } = history
  const [appliedConfig, setAppliedConfig] = useState('')

  // A profile that imports a template is not the same thing as the text in its
  // file. Every read below goes through the resolved text so inherited settings
  // show up; writes still go to configText, so changing an inherited value
  // writes an override into this profile rather than editing the template.
  const includes = useConfigIncludes(configText, INCLUDE_ROOT)
  const readText = includes.effectiveText

  const sensitivityConfig = useSensitivityConfig({ configText, readText, setConfigText })
  const touchpadConfig = useTouchpadConfig({ configText, readText, setConfigText })
  const gripConfig = useGripConfig({ configText, readText, setConfigText })
  const stickConfig = useStickConfig({ configText, readText, setConfigText })
  const bindingsConfig = useBindingsConfig({ configText, readText, setConfigText })

  const ignoredGyroDevices = useMemo(() => {
    const raw = getKeymapValue(readText, keyName.IGNORE_GYRO_DEVICES) ?? ''
    return raw
      .split(/\s+/)
      .map(token => token.trim())
      .filter(Boolean)
      .map(token => token.toLowerCase())
  }, [readText])

  const hasPendingChanges = configText !== appliedConfig || sensitivityConfig.hasPendingSensitivityChanges
  const handleCancel = () => {
    sensitivityConfig.resetPendingSensitivityChanges()
    setConfigText(appliedConfig)
  }

  return {
    configText,
    // The text the runtime would execute: this profile with its imports
    // resolved in place. Read-only -- never save it over a profile.
    effectiveConfigText: readText,
    configIncludes: includes,
    setConfigText,
    resetConfigHistory: history.reset,
    canUndo: history.canUndo,
    canRedo: history.canRedo,
    undo: () => { sensitivityConfig.resetPendingSensitivityChanges(); history.undo() },
    redo: () => { sensitivityConfig.resetPendingSensitivityChanges(); history.redo() },
    appliedConfig,
    setAppliedConfig,
    hasPendingChanges,
    handleCancel,
    ignoredGyroDevices,
    finalizePendingValues: sensitivityConfig.finalizePendingValues,
    // Sensitivity slice
    sensitivityView: sensitivityConfig.sensitivityView,
    setSensitivityView: sensitivityConfig.setSensitivityView,
    sensitivityModeshiftButton: sensitivityConfig.sensitivityModeshiftButton,
    sensitivity: sensitivityConfig.sensitivity,
    modeshiftSensitivity: sensitivityConfig.modeshiftSensitivity,
    activeSensitivityPrefix: sensitivityConfig.activeSensitivityPrefix,
    baseMode: sensitivityConfig.baseMode,
    modeshiftMode: sensitivityConfig.modeshiftMode,
    selectedBaseMode: sensitivityConfig.selectedBaseMode,
    selectedModeshiftMode: sensitivityConfig.selectedModeshiftMode,
    holdPressTimeSeconds: sensitivityConfig.holdPressTimeSeconds,
    holdPressTimeIsCustom: sensitivityConfig.holdPressTimeIsCustom,
    doublePressWindowSeconds: sensitivityConfig.doublePressWindowSeconds,
    doublePressWindowIsCustom: sensitivityConfig.doublePressWindowIsCustom,
    simPressWindowSeconds: sensitivityConfig.simPressWindowSeconds,
    simPressWindowIsCustom: sensitivityConfig.simPressWindowIsCustom,
    lightBarColor: sensitivityConfig.lightBarColor,
    handleLightBarChange: sensitivityConfig.handleLightBarChange,
    triggerThresholdValue: sensitivityConfig.triggerThresholdValue,
    handleSensitivityModeshiftButtonChange: sensitivityConfig.handleSensitivityModeshiftButtonChange,
    handleThresholdChange: sensitivityConfig.handleThresholdChange,
    handleCutoffSpeedChange: sensitivityConfig.handleCutoffSpeedChange,
    handleCutoffRecoveryChange: sensitivityConfig.handleCutoffRecoveryChange,
    handleSmoothTimeChange: sensitivityConfig.handleSmoothTimeChange,
    handleSmoothThresholdChange: sensitivityConfig.handleSmoothThresholdChange,
    handleSmoothingDecayChange: sensitivityConfig.handleSmoothingDecayChange,
    handleOneEuroFilterChange: sensitivityConfig.handleOneEuroFilterChange,
    handleOneEuroMinCutoffChange: sensitivityConfig.handleOneEuroMinCutoffChange,
    handleOneEuroSpeedCoeffChange: sensitivityConfig.handleOneEuroSpeedCoeffChange,
    handleAngleSnapChange: sensitivityConfig.handleAngleSnapChange,
    handleAngleSnapSmoothChange: sensitivityConfig.handleAngleSnapSmoothChange,
    handleDecelBrakeStrengthChange: sensitivityConfig.handleDecelBrakeStrengthChange,
    handleDecelBrakeThresholdChange: sensitivityConfig.handleDecelBrakeThresholdChange,
    handleGyroClickDampenChange: sensitivityConfig.handleGyroClickDampenChange,
    handleTickTimeChange: sensitivityConfig.handleTickTimeChange,
    handleHoldPressTimeChange: sensitivityConfig.handleHoldPressTimeChange,
    handleDoublePressWindowChange: sensitivityConfig.handleDoublePressWindowChange,
    handleSimPressWindowChange: sensitivityConfig.handleSimPressWindowChange,
    handleTriggerThresholdChange: sensitivityConfig.handleTriggerThresholdChange,
    handleGyroSpaceChange: sensitivityConfig.handleGyroSpaceChange,
    handleGyroAxisXChange: sensitivityConfig.handleGyroAxisXChange,
    handleGyroAxisYChange: sensitivityConfig.handleGyroAxisYChange,
    handleGyroOutputChange: sensitivityConfig.handleGyroOutputChange,
    handleDualSensChange: sensitivityConfig.handleDualSensChange,
    handleStaticSensChange: sensitivityConfig.handleStaticSensChange,
    handleRollContributionChange: sensitivityConfig.handleRollContributionChange,
    handleModeSelection: sensitivityConfig.handleModeSelection,
    handleInGameSensChange: sensitivityConfig.handleInGameSensChange,
    handleRealWorldCalibrationChange: sensitivityConfig.handleRealWorldCalibrationChange,
    switchToStaticMode: sensitivityConfig.switchToStaticMode,
    handleAccelCurveChange: sensitivityConfig.handleAccelCurveChange,
    handleNaturalVHalfChange: sensitivityConfig.handleNaturalVHalfChange,
    handlePowerVRefChange: sensitivityConfig.handlePowerVRefChange,
    handlePowerExponentChange: sensitivityConfig.handlePowerExponentChange,
    handleJumpTauChange: sensitivityConfig.handleJumpTauChange,
    handleSigmoidMidChange: sensitivityConfig.handleSigmoidMidChange,
    handleSigmoidWidthChange: sensitivityConfig.handleSigmoidWidthChange,
    switchToAccelMode: sensitivityConfig.switchToAccelMode,
    // Touchpad slice
    touchpadModeValue: touchpadConfig.touchpadModeValue,
    touchpadMinCutoffValue: touchpadConfig.touchpadMinCutoffValue,
    touchpadSpeedCoeffValue: touchpadConfig.touchpadSpeedCoeffValue,
    touchpadTrackballDecayValue: touchpadConfig.touchpadTrackballDecayValue,
    touchpadTrackballMinVelocityValue: touchpadConfig.touchpadTrackballMinVelocityValue,
    handleTouchpadMinCutoffChange: touchpadConfig.handleTouchpadMinCutoffChange,
    handleTouchpadSpeedCoeffChange: touchpadConfig.handleTouchpadSpeedCoeffChange,
    handleTouchpadTrackballDecayChange: touchpadConfig.handleTouchpadTrackballDecayChange,
    handleTouchpadTrackballMinVelocityChange: touchpadConfig.handleTouchpadTrackballMinVelocityChange,
    touchpadMovementThresholdValue: touchpadConfig.touchpadMovementThresholdValue,
    handleTouchpadMovementThresholdChange: touchpadConfig.handleTouchpadMovementThresholdChange,
    touchpadHapticIntensityValue: touchpadConfig.touchpadHapticIntensityValue,
    touchpadHapticEffectValue: touchpadConfig.touchpadHapticEffectValue,
    touchpadHapticIntervalValue: touchpadConfig.touchpadHapticIntervalValue,
    touchpadClickHapticIntensityValue: touchpadConfig.touchpadClickHapticIntensityValue,
    touchpadClickHapticEffectValue: touchpadConfig.touchpadClickHapticEffectValue,
    handleTouchpadHapticIntensityChange: touchpadConfig.handleTouchpadHapticIntensityChange,
    handleTouchpadHapticEffectChange: touchpadConfig.handleTouchpadHapticEffectChange,
    handleTouchpadHapticIntervalChange: touchpadConfig.handleTouchpadHapticIntervalChange,
    handleTouchpadClickHapticIntensityChange: touchpadConfig.handleTouchpadClickHapticIntensityChange,
    handleTouchpadClickHapticEffectChange: touchpadConfig.handleTouchpadClickHapticEffectChange,
    touchpadReleaseHapticIntensityValue: touchpadConfig.touchpadReleaseHapticIntensityValue,
    touchpadReleaseHapticEffectValue: touchpadConfig.touchpadReleaseHapticEffectValue,
    handleTouchpadReleaseHapticIntensityChange: touchpadConfig.handleTouchpadReleaseHapticIntensityChange,
    handleTouchpadReleaseHapticEffectChange: touchpadConfig.handleTouchpadReleaseHapticEffectChange,
    touchpadClickDampenValue: touchpadConfig.touchpadClickDampenValue,
    touchpadClickDampenThresholdValue: touchpadConfig.touchpadClickDampenThresholdValue,
    handleTouchpadClickDampenChange: touchpadConfig.handleTouchpadClickDampenChange,
    handleTouchpadClickDampenThresholdChange: touchpadConfig.handleTouchpadClickDampenThresholdChange,
    leftGripHapticsValue: gripConfig.leftGripHapticsValue,
    rightGripHapticsValue: gripConfig.rightGripHapticsValue,
    handleLeftGripHapticsChange: gripConfig.handleLeftGripHapticsChange,
    handleRightGripHapticsChange: gripConfig.handleRightGripHapticsChange,
    gripSensorRangeValue: gripConfig.gripSensorRangeValue,
    gripFlickerGuardValue: gripConfig.gripFlickerGuardValue,
    gripHapticIntensityValue: gripConfig.gripHapticIntensityValue,
    gripHapticEffectValue: gripConfig.gripHapticEffectValue,
    gripReleaseHapticIntensityValue: gripConfig.gripReleaseHapticIntensityValue,
    gripReleaseHapticEffectValue: gripConfig.gripReleaseHapticEffectValue,
    handleGripSensorRangeChange: gripConfig.handleGripSensorRangeChange,
    handleGripFlickerGuardChange: gripConfig.handleGripFlickerGuardChange,
    handleGripHapticIntensityChange: gripConfig.handleGripHapticIntensityChange,
    handleGripHapticEffectChange: gripConfig.handleGripHapticEffectChange,
    handleGripReleaseHapticIntensityChange: gripConfig.handleGripReleaseHapticIntensityChange,
    handleGripReleaseHapticEffectChange: gripConfig.handleGripReleaseHapticEffectChange,
    leftTouchpadModeValue: touchpadConfig.leftTouchpadModeValue,
    rightTouchpadModeValue: touchpadConfig.rightTouchpadModeValue,
    leftGridSizeValue: touchpadConfig.leftGridSizeValue,
    rightGridSizeValue: touchpadConfig.rightGridSizeValue,
    leftTouchpadSensitivityValue: touchpadConfig.leftTouchpadSensitivityValue,
    rightTouchpadSensitivityValue: touchpadConfig.rightTouchpadSensitivityValue,
    leftTouchpadDualStageModeValue: touchpadConfig.leftTouchpadDualStageModeValue,
    rightTouchpadDualStageModeValue: touchpadConfig.rightTouchpadDualStageModeValue,
    gridSizeValue: touchpadConfig.gridSizeValue,
    touchpadSensitivityValue: touchpadConfig.touchpadSensitivityValue,
    touchpadSensitivityYValue: touchpadConfig.touchpadSensitivityYValue,
    leftTouchpadSensitivityYValue: touchpadConfig.leftTouchpadSensitivityYValue,
    rightTouchpadSensitivityYValue: touchpadConfig.rightTouchpadSensitivityYValue,
    touchpadDualStageModeValue: touchpadConfig.touchpadDualStageModeValue,
    gridRequiresClickValue: touchpadConfig.gridRequiresClickValue,
    leftGridRequiresClickValue: touchpadConfig.leftGridRequiresClickValue,
    rightGridRequiresClickValue: touchpadConfig.rightGridRequiresClickValue,
    touchStickModeValue: touchpadConfig.touchStickModeValue,
    leftTouchStickModeValue: touchpadConfig.leftTouchStickModeValue,
    rightTouchStickModeValue: touchpadConfig.rightTouchStickModeValue,
    touchDeadzoneInnerValue: touchpadConfig.touchDeadzoneInnerValue,
    leftTouchDeadzoneInnerValue: touchpadConfig.leftTouchDeadzoneInnerValue,
    rightTouchDeadzoneInnerValue: touchpadConfig.rightTouchDeadzoneInnerValue,
    touchRingModeValue: touchpadConfig.touchRingModeValue,
    leftTouchRingModeValue: touchpadConfig.leftTouchRingModeValue,
    rightTouchRingModeValue: touchpadConfig.rightTouchRingModeValue,
    touchStickRadiusValue: touchpadConfig.touchStickRadiusValue,
    leftTouchStickRadiusValue: touchpadConfig.leftTouchStickRadiusValue,
    rightTouchStickRadiusValue: touchpadConfig.rightTouchStickRadiusValue,
    touchStickAxisValue: touchpadConfig.touchStickAxisValue,
    leftTouchStickAxisValue: touchpadConfig.leftTouchStickAxisValue,
    rightTouchStickAxisValue: touchpadConfig.rightTouchStickAxisValue,
    touchpadWarnings: touchpadConfig.touchpadWarnings,
    handleTouchpadModeChange: touchpadConfig.handleTouchpadModeChange,
    handleLeftTouchpadModeChange: touchpadConfig.handleLeftTouchpadModeChange,
    handleRightTouchpadModeChange: touchpadConfig.handleRightTouchpadModeChange,
    handleGridSizeChange: touchpadConfig.handleGridSizeChange,
    gridShapeValue: touchpadConfig.gridShapeValue,
    leftGridShapeValue: touchpadConfig.leftGridShapeValue,
    rightGridShapeValue: touchpadConfig.rightGridShapeValue,
    gridDeadzoneValue: touchpadConfig.gridDeadzoneValue,
    leftGridDeadzoneValue: touchpadConfig.leftGridDeadzoneValue,
    rightGridDeadzoneValue: touchpadConfig.rightGridDeadzoneValue,
    handleGridShapeChange: touchpadConfig.handleGridShapeChange,
    handleLeftGridShapeChange: touchpadConfig.handleLeftGridShapeChange,
    handleRightGridShapeChange: touchpadConfig.handleRightGridShapeChange,
    handleGridDeadzoneChange: touchpadConfig.handleGridDeadzoneChange,
    handleLeftGridDeadzoneChange: touchpadConfig.handleLeftGridDeadzoneChange,
    handleRightGridDeadzoneChange: touchpadConfig.handleRightGridDeadzoneChange,
    handleLeftGridSizeChange: touchpadConfig.handleLeftGridSizeChange,
    handleRightGridSizeChange: touchpadConfig.handleRightGridSizeChange,
    handleTouchpadSensitivityChange: touchpadConfig.handleTouchpadSensitivityChange,
    handleTouchpadSensitivityYChange: touchpadConfig.handleTouchpadSensitivityYChange,
    handleLeftTouchpadSensitivityYChange: touchpadConfig.handleLeftTouchpadSensitivityYChange,
    handleRightTouchpadSensitivityYChange: touchpadConfig.handleRightTouchpadSensitivityYChange,
    handleLeftTouchpadSensitivityChange: touchpadConfig.handleLeftTouchpadSensitivityChange,
    handleRightTouchpadSensitivityChange: touchpadConfig.handleRightTouchpadSensitivityChange,
    handleTouchpadDualStageModeChange: touchpadConfig.handleTouchpadDualStageModeChange,
    handleLeftTouchpadDualStageModeChange: touchpadConfig.handleLeftTouchpadDualStageModeChange,
    handleRightTouchpadDualStageModeChange: touchpadConfig.handleRightTouchpadDualStageModeChange,
    handleGridRequiresClickChange: touchpadConfig.handleGridRequiresClickChange,
    handleLeftGridRequiresClickChange: touchpadConfig.handleLeftGridRequiresClickChange,
    handleRightGridRequiresClickChange: touchpadConfig.handleRightGridRequiresClickChange,
    handleTouchStickModeChange: touchpadConfig.handleTouchStickModeChange,
    handleLeftTouchStickModeChange: touchpadConfig.handleLeftTouchStickModeChange,
    handleRightTouchStickModeChange: touchpadConfig.handleRightTouchStickModeChange,
    handleTouchDeadzoneInnerChange: touchpadConfig.handleTouchDeadzoneInnerChange,
    handleLeftTouchDeadzoneInnerChange: touchpadConfig.handleLeftTouchDeadzoneInnerChange,
    handleRightTouchDeadzoneInnerChange: touchpadConfig.handleRightTouchDeadzoneInnerChange,
    handleTouchRingModeChange: touchpadConfig.handleTouchRingModeChange,
    handleLeftTouchRingModeChange: touchpadConfig.handleLeftTouchRingModeChange,
    handleRightTouchRingModeChange: touchpadConfig.handleRightTouchRingModeChange,
    handleTouchStickRadiusChange: touchpadConfig.handleTouchStickRadiusChange,
    handleLeftTouchStickRadiusChange: touchpadConfig.handleLeftTouchStickRadiusChange,
    handleRightTouchStickRadiusChange: touchpadConfig.handleRightTouchStickRadiusChange,
    handleTouchStickAxisChange: touchpadConfig.handleTouchStickAxisChange,
    handleLeftTouchStickAxisChange: touchpadConfig.handleLeftTouchStickAxisChange,
    handleRightTouchStickAxisChange: touchpadConfig.handleRightTouchStickAxisChange,
    touchpadAccelerationValue: touchpadConfig.touchpadAccelerationValue,
    handleAcceleration: touchpadConfig.handleTouchpadAccelerationChange,
    touchpadAccelValues: touchpadConfig.touchpadAccelValues,
    accelCurveLinkValue: touchpadConfig.accelCurveLinkValue,
    handleTouchpadAccelCurveChange: touchpadConfig.handleTouchpadAccelCurveChange,
    handleTouchpadAccelParamChange: touchpadConfig.handleTouchpadAccelParamChange,
    handleAccelCurveLinkChange: touchpadConfig.handleAccelCurveLinkChange,
    // Stick slice
    handleStickDeadzoneChange: stickConfig.handleStickDeadzoneChange,
    handleStickModeChange: stickConfig.handleStickModeChange,
    handleRingModeChange: stickConfig.handleRingModeChange,
    handleStickModeShiftChange: stickConfig.handleStickModeShiftChange,
    handleAdaptiveTriggerChange: stickConfig.handleAdaptiveTriggerChange,
    stickAimHandlers: stickConfig.stickAimHandlers,
    stickFlickSettings: stickConfig.stickFlickSettings,
    stickFlickHandlers: stickConfig.stickFlickHandlers,
    mouseRingRadiusValue: stickConfig.mouseRingRadiusValue,
    handleMouseRingRadiusChange: stickConfig.handleMouseRingRadiusChange,
    counterOsMouseSpeedEnabled: stickConfig.counterOsMouseSpeedEnabled,
    handleCounterOsMouseSpeedChange: stickConfig.handleCounterOsMouseSpeedChange,
    stickDeadzoneDefaults: stickConfig.stickDeadzoneDefaults,
    leftStickDeadzone: stickConfig.leftStickDeadzone,
    rightStickDeadzone: stickConfig.rightStickDeadzone,
    stickModes: stickConfig.stickModes,
    stickModeShiftAssignments: stickConfig.stickModeShiftAssignments,
    stickAimSettings: stickConfig.stickAimSettings,
    adaptiveTriggerValue: stickConfig.adaptiveTriggerValue,
    zlModeValue: stickConfig.zlModeValue,
    zrModeValue: stickConfig.zrModeValue,
    handleZlModeChange: stickConfig.handleZlModeChange,
    handleZrModeChange: stickConfig.handleZrModeChange,
    handleStickSensChange: stickConfig.handleStickSensChange,
    handleStickPowerChange: stickConfig.handleStickPowerChange,
    handleStickAccelerationRateChange: stickConfig.handleStickAccelerationRateChange,
    handleStickAccelerationCapChange: stickConfig.handleStickAccelerationCapChange,
    handleToggleIgnoreGyroDevice: stickConfig.handleToggleIgnoreGyroDevice,
    scrollSensValue: stickConfig.scrollSensValue,
    handleScrollSensChange: stickConfig.handleScrollSensChange,
    // Bindings slice
    handleFaceButtonBindingChange: bindingsConfig.handleFaceButtonBindingChange,
    handleModifierChange: bindingsConfig.handleModifierChange,
    handleSpecialActionAssignment: bindingsConfig.handleSpecialActionAssignment,
    handleClearSpecialAction: bindingsConfig.handleClearSpecialAction,
    gyroActivation: bindingsConfig.gyroActivation,
    handleGyroActivationModeChange: bindingsConfig.handleGyroActivationModeChange,
    handleGyroActivationButtonChange: bindingsConfig.handleGyroActivationButtonChange,
    trackballDecayValue: bindingsConfig.trackballDecayValue,
    handleBindGamepadPassthrough: bindingsConfig.handleBindGamepadPassthrough,
    handleBindDirectionsToWasd: bindingsConfig.handleBindDirectionsToWasd,
    handleTrackballDecayChange: bindingsConfig.handleTrackballDecayChange,
    virtualControllerType: bindingsConfig.virtualControllerType,
    virtualControllerWarnings: bindingsConfig.virtualControllerWarnings,
    handleVirtualControllerTypeChange: bindingsConfig.handleVirtualControllerTypeChange,
    resetPendingSensitivityChanges: sensitivityConfig.resetPendingSensitivityChanges,
  }
}
