/** Concept help shared by dropdowns across the editor. */
export const OPTION_HELP: Record<string, string> = {
  RECTANGLE: 'Arrange pad regions in rows and columns. Each cell has its own binding.',
  FOUR_WAY: 'Split the pad into four directional regions: up, right, down and left.',
  EIGHT_WAY: 'Split the pad into eight directional regions, including diagonals.',
  RADIAL: 'Arrange pad regions as wedges around the centre.',
  INNER: 'Activate the ring binding inside the ring threshold, near the centre.',
  OUTER: 'Activate the ring binding outside the ring threshold, near the edge.',
  STANDARD: 'Keep the input axes in their normal directions.',
  INVERTED: 'Reverse the direction of the configured axes.',
  X_INVERTED: 'Reverse horizontal movement while keeping vertical movement normal.',
  Y_INVERTED: 'Reverse vertical movement while keeping horizontal movement normal.',
  HYBRID_AIM: 'Move the mouse by moving the stick, with optional continuous movement at the edge. Return suppression can ignore movement back toward centre. Example: make small aim adjustments, then push to the edge for a longer turn.',
  MOUSE_RING: 'Place the cursor on a fixed-radius circle around the screen centre. Stick direction sets the position; tilt distance does not set the radius. Example: select an item in a game’s mouse-driven radial weapon wheel.',
  INNER_RING: 'Keep directional bindings active and use the ring binding while tilted lightly, outside the centre deadzone. Example: bind WASD to directions and a walk modifier to the ring for slow movement at light tilt.',
  OUTER_RING: 'Keep directional bindings active and use the ring binding at strong tilt. Example: bind WASD to directions and Sprint to the ring to run when you push farther out.',
  LEFT_ANGLE_TO_X: 'Convert stick angle toward left or right into the virtual left stick’s horizontal output; tilt distance also affects strength. Requires a virtual controller. Example: steer by sweeping an arc across the top of the stick.',
  LEFT_ANGLE_TO_Y: 'Convert stick angle toward up or down into the virtual left stick’s vertical output; tilt distance also affects strength. Requires a virtual controller. Example: control forward and reverse movement by sweeping from the side toward up or down.',
  RIGHT_ANGLE_TO_X: 'Convert stick angle toward left or right into the virtual right stick’s horizontal output; tilt distance also affects strength. Requires a virtual controller. Example: control horizontal camera movement with an arc while leaving vertical aiming to another input.',
  RIGHT_ANGLE_TO_Y: 'Convert stick angle toward up or down into the virtual right stick’s vertical output; tilt distance also affects strength. Requires a virtual controller. Example: control camera pitch with an arc while another input handles horizontal turning.',
  LEFT_WIND_X: 'Rotate the stick to accumulate steering on the virtual left stick’s horizontal axis. Moving inward lets it unwind at the configured rate. Requires a virtual controller. Example: turn the stick like a steering wheel in a driving game.',
  RIGHT_WIND_X: 'Rotate the stick to accumulate steering on the virtual right stick’s horizontal axis. Moving inward lets it unwind at the configured rate. Requires a virtual controller. Example: use wheel-like steering in a game configured to steer with the right stick.',
  ANY: 'Activate when at least one of the listed input conditions matches.',
  ALL: 'Activate only when every listed input condition matches at the same time.',
  threshold: 'Activate the soft-press binding when trigger travel crosses the configured threshold.',
  hair: 'Use changes in trigger travel for fast activation and release instead of a fixed travel threshold.',
  TICK: 'Play a brief tactile tick. Strength controls how pronounced it feels.',
  CLICK: 'Play the controller’s click effect for a button-like tactile response.',
  TONE: 'Play the controller’s tonal vibration effect.',
  RUMBLE: 'Play the controller’s rumble effect.',
  SWEEP: 'Play the controller’s sweeping vibration effect.',
  PULSE: 'Play the pulse used by Steam’s grip calibration.',
  TAP: 'Play a pad click followed by the grip-calibration pulse.',
  static: 'Use a constant sensitivity regardless of movement speed.',
  accel: 'Change sensitivity with movement speed using the configured acceleration curve.',
  GYRO_USES_TOUCHPAD: 'Use the trackpad acceleration curve for gyro input as well.',
  TOUCHPAD_USES_GYRO: 'Use the gyro acceleration curve for trackpad input as well.',
  regular: 'Press: activate when the input is pressed and release when it is let go.',
  tap: 'Tap: activate for a short press released before Hold press time. A longer press uses the Hold binding instead.',
  hold: 'Hold: activate after holding the input for Hold press time; release when you let go.',
  double: 'Double press: activate when pressed twice within the double-press window.',
  release: 'Release: activate when the input is let go.',
  turbo: 'Turbo: repeat the output while the input stays held. Open this action’s cog to set its turbo interval.',
  chord: 'Chord: use this binding while another chosen input is already held. Useful for a modifier or alternate layer.',
  simultaneous: 'Simultaneous: press this and the chosen input together within the simultaneous-press window.',
  diagonal: 'Diagonal: activate when both of the chosen direction inputs are held.',
  keyboard: 'Keyboard: send a keyboard key to the game. Capture a key or choose one with Keyboard…',
  mouse: 'Mouse: send a mouse button, such as left click to fire or right click to aim.',
  wheel: 'Mouse wheel: send a scroll-up or scroll-down step.',
  virtualController: 'Virtual controller: send a button to the emulated Xbox or PlayStation gamepad. The virtual controller must be enabled.',
  haptic: 'Haptic: play a vibration pulse on the selected actuator, where the controller supports it.',
  special: 'Special action: control a mapper feature, such as gyro activation or calibration.',
  loadConfig:
    'Load configuration: switch to another of your configurations when this input activates. The new one stays loaded until something switches again, so bind a way back inside it.',
  command: 'Command: run a JoyShockMapper command when this input activates.',
  raw: 'Raw binding: enter JoyShockMapper binding syntax directly. Use this for bindings the visual editor cannot express.',
  normal: 'Hold the output for as long as this trigger remains active.',
  tapOnce: 'Send one brief press and release each time this trigger activates.',
  toggle: 'Press once to keep the output held; press again to release it.',
  releaseOnly: 'Release an output that was previously held.',
  NO_FULL: 'Soft press only. No separate full-pull action.',
  NO_SKIP: 'Soft press activates first. Pull fully to activate the full-pull action too.',
  NO_SKIP_EXCLUSIVE: 'Soft press activates first, then releases while full pull is active.',
  MUST_SKIP: 'Wait briefly to distinguish a soft pull from a quick full pull. A quick full pull skips the soft action.',
  MAY_SKIP: 'A quick full pull may skip the soft action; a slower pull allows both stages.',
  MUST_SKIP_R: 'Soft pull activates immediately. A quick full pull replaces it; after the decision window, full pull cannot replace the soft action.',
  MAY_SKIP_R: 'Soft pull activates immediately. A quick full pull replaces it; a slower full pull adds the full action alongside it.',
  X_LT: 'Analog left trigger passthrough to the virtual gamepad. Digital soft-press threshold and flicker guard do not apply.',
  X_RT: 'Analog right trigger passthrough to the virtual gamepad. Digital soft-press threshold and flicker guard do not apply.',
  GRID_AND_STICK: 'Divide the pad into bindable regions and optionally use its motion as a touch stick. Require click lets you rest over a region without activating it.',
  MOUSE: 'Move the mouse with this input. Trackpad acceleration, smoothing and release behavior are on Trackpad tuning.',
  PS_TOUCHPAD: 'Forward touch coordinates to the virtual PlayStation controller for games that use its touchpad.',
  STRETCH: 'Stretch: the whole pad is the whole area, whatever their shapes. A square pad over a wide strip moves faster sideways than up and down.',
  UNIFORM: 'Keep pad shape: the same cursor travel per millimetre in both directions. The pad is scaled to cover the area and centred on it; its spare travel stops at the area’s edge.',
  LEFT_STICK: 'Send analog movement to the virtual gamepad’s left stick. Requires an enabled virtual controller. Example: retain variable walking speed in a game with native controller support.',
  RIGHT_STICK: 'Send analog movement to the virtual gamepad’s right stick. Requires an enabled virtual controller. Example: control the camera in a game that expects a gamepad.',
  XBOX: 'Emulate an Xbox gamepad. Existing equivalent virtual button bindings are converted automatically.',
  DS4: 'Emulate a PlayStation DualShock 4. Existing equivalent virtual button bindings are converted automatically.',
  LINEAR: 'Sensitivity changes evenly between Slow speed and Fast speed.',
  NATURAL: 'Sensitivity rises smoothly toward the maximum; half-speed controls how quickly it approaches it.',
  QUADRATIC: 'Sensitivity rises gently at first, then more quickly as input speed increases.',
  POWER: 'A power-shaped response. Reference speed and exponent control where acceleration builds.',
  SIGMOID: 'An S-shaped response: a gentle start, a stronger middle rise and a gentle finish.',
  JUMP: 'Switch from minimum to maximum sensitivity around the chosen speed. Transition softness rounds the step.',
  NO_MOUSE: 'Use the assigned up, down, left and right buttons while the stick is tilted. Example: bind WASD for movement in a keyboard-only game.',
  AIM: 'Move the mouse continuously while the stick is tilted; more tilt changes speed according to your response curve. Example: control a camera in a game that accepts mouse input.',
  FLICK: 'Push toward the edge to turn horizontally by that direction, then rotate around the edge to keep turning. Example: flick down for a calibrated 180-degree turn and use gyro to aim up and down.',
  FLICK_ONLY: 'Turn horizontally when you push toward the edge, without further turning as you rotate the stick. Re-centre before another flick. Example: make quick 90- or 180-degree turns while gyro handles aiming.',
  ROTATE_ONLY: 'Turn horizontally by rotating the stick around its edge, without a jump when you first push it out. Example: sweep the camera smoothly while using gyro for precise aim.',
  // The same word on a trackpad and on a stick, meaning two different things.
  MOUSE_AREA: 'On a joystick, moving the stick moves the mouse by a matching distance; moving back reverses that movement. Example: make bounded cursor adjustments from a starting position. On a trackpad, map touch position to a screen rectangle, such as an inventory or hotbar.',
  SCROLL_WHEEL: 'Rotate the stick to pulse its left or right binding in steps. Assign those actions yourself. Example: bind scroll up and scroll down to cycle weapons, or arrow keys to step through a list.',
  RADIAL_MENU: 'Point beyond the menu deadzone to activate a segment’s binding; changing segment or returning to centre releases it. Example: assign weapon keys or abilities to a wheel of shortcuts.',
  LOCAL: 'Use the controller’s own rotation axes. The relationship changes as you tilt your grip.',
  YAW_PLUS_ROLL: 'Combine yaw and roll contributions for horizontal turning.',
  PLAYER_TURN: 'Combine yaw and roll relative to the player’s grip for natural horizontal turning.',
  WORLD_TURN: 'Turn around the gravity-aligned vertical axis, accommodating a tilted controller.',
  PLAYER_LEAN: 'Use gravity to combine rotation axes for horizontal aim by leaning the controller.',
  WORLD_LEAN: 'Horizontal aim from lean around the gravity-aligned forward axis.',
  NONE: 'Disable this output or mode explicitly. This differs from clearing an override to inherit a value.',
  ON: 'Enable this behavior.',
  OFF: 'Disable this behavior.',
}
