/** Concept help shared by dropdowns across the editor. */
export const OPTION_HELP: Record<string, string> = {
  regular: 'Press: activate when the input is pressed and release when it is let go.',
  tap: 'Tap: activate for a short press released before Hold press time. A longer press uses the Hold binding instead.',
  hold: 'Hold: activate after holding the input for Hold press time; release when you let go.',
  double: 'Double press: activate when pressed twice within the double-press window.',
  release: 'Release: activate when the input is let go.',
  turbo: 'Turbo: repeat the output while the input stays held. Advanced settings control the repeat timing.',
  chord: 'Chord: use this binding while another chosen input is already held. Useful for a modifier or alternate layer.',
  simultaneous: 'Simultaneous: press this and the chosen input together within the simultaneous-press window.',
  diagonal: 'Diagonal: activate when both of the chosen direction inputs are held.',
  keyboard: 'Keyboard: send a keyboard key to the game. Capture a key or choose one with Keyboard…',
  mouse: 'Mouse: send a mouse button, such as left click to fire or right click to aim.',
  wheel: 'Mouse wheel: send a scroll-up or scroll-down step.',
  virtualController: 'Virtual controller: send a button to the emulated Xbox or PlayStation gamepad. The virtual controller must be enabled.',
  haptic: 'Haptic: play a vibration pulse on the selected actuator, where the controller supports it.',
  special: 'Special action: control a mapper feature, such as gyro activation or calibration.',
  loadConfig:
    'Load configuration: switch to another of your configurations when this input activates. The new one stays loaded until something switches again, so bind a way back inside it.',
  command: 'Command: run a JoyShockMapper command when this input activates.',
  raw: 'Raw binding: enter JoyShockMapper binding syntax directly. Use this for bindings the visual editor cannot express.',
  normal: 'Hold the output for as long as this trigger remains active.',
  tapOnce: 'Send one brief press and release each time this trigger activates.',
  toggle: 'Press once to keep the output held; press again to release it.',
  releaseOnly: 'Release an output that was previously held.',
  NO_FULL: 'Soft press only. No separate full-pull action.',
  NO_SKIP: 'Soft press activates first. Pull fully to activate the full-pull action too.',
  NO_SKIP_EXCLUSIVE: 'Soft press activates first, then releases while full pull is active.',
  MUST_SKIP: 'Wait briefly to distinguish a soft pull from a quick full pull. A quick full pull skips the soft action.',
  MAY_SKIP: 'A quick full pull may skip the soft action; a slower pull allows both stages.',
  MUST_SKIP_R: 'Like Must skip, with responsive full-pull release handling.',
  MAY_SKIP_R: 'Like May skip, with responsive full-pull release handling.',
  X_LT: 'Analog left trigger passthrough to the virtual gamepad. Digital soft-press threshold and flicker guard do not apply.',
  X_RT: 'Analog right trigger passthrough to the virtual gamepad. Digital soft-press threshold and flicker guard do not apply.',
  GRID_AND_STICK: 'Divide the pad into bindable regions and optionally use its motion as a touch stick. Require click lets you rest over a region without activating it.',
  MOUSE: 'Move the mouse with this input. Trackpad acceleration, smoothing and release behavior are on Trackpad tuning.',
  PS_TOUCHPAD: 'Forward touch coordinates to the virtual PlayStation controller for games that use its touchpad.',
  LEFT_STICK: 'Forward movement to the virtual gamepad’s left stick. A virtual controller must be enabled.',
  RIGHT_STICK: 'Forward movement to the virtual gamepad’s right stick. A virtual controller must be enabled.',
  XBOX: 'Emulate an Xbox gamepad. Existing equivalent virtual button bindings are converted automatically.',
  DS4: 'Emulate a PlayStation DualShock 4. Existing equivalent virtual button bindings are converted automatically.',
  LINEAR: 'Sensitivity changes evenly between Slow speed and Fast speed.',
  NATURAL: 'Sensitivity rises smoothly toward the maximum; half-speed controls how quickly it approaches it.',
  QUADRATIC: 'Sensitivity rises gently at first, then more quickly as input speed increases.',
  POWER: 'A power-shaped response. Reference speed and exponent control where acceleration builds.',
  SIGMOID: 'An S-shaped response: a gentle start, a stronger middle rise and a gentle finish.',
  JUMP: 'Switch from minimum to maximum sensitivity around the chosen speed. Transition softness rounds the step.',
  NO_MOUSE: 'Use directional button bindings without moving the mouse. Useful for WASD movement.',
  AIM: 'Move the mouse continuously while the stick is tilted. Sensitivity controls turning speed.',
  FLICK: 'Point the stick to turn toward that direction; rotate it around the edge for further turning. Typically paired with gyro aiming.',
  FLICK_ONLY: 'Turn toward the direction you point the stick, without continuous edge rotation.',
  ROTATE_ONLY: 'Rotate the camera by moving the stick around its edge, without an initial flick.',
  MOUSE_AREA: 'Map the stick position to an area around a mouse anchor. Useful for cursor-based controls.',
  SCROLL_WHEEL: 'Rotate the stick to produce scrolling rather than mouse movement.',
  RADIAL_MENU: 'Choose among a wheel of actions by pointing the stick at a segment.',
  LOCAL: 'Use the controller’s own rotation axes. The relationship changes as you tilt your grip.',
  YAW_PLUS_ROLL: 'Combine yaw and roll contributions for horizontal turning.',
  PLAYER_TURN: 'Combine yaw and roll relative to the player’s grip for natural horizontal turning.',
  WORLD_TURN: 'Turn around the gravity-aligned vertical axis, accommodating a tilted controller.',
  NONE: 'Disable this output or mode explicitly. This differs from clearing an override to inherit a value.',
  ON: 'Enable this behavior.',
  OFF: 'Disable this behavior.',
}
